// Venom console — Shell entry. Compiled by Vite (no in-browser Babel, no CDN React).
// Screen registry is generated by scripts/migrate-screens-to-vite.js into
// screen-registry.json; re-run it if a screen is renamed or moved between files.
import * as React from "react";
import { createRoot } from "react-dom/client";
import { Icon, ThemeSwitcher, DensityToggle, OwnerSessionStatus } from "../../src/index";
import type { ThemeName } from "../../src/index";
import type { DensityName } from "../../src/index";
import * as OperateScreens from "./screens-operate";
import * as InsightsScreens from "./screens-insights";
import * as ManageScreens from "./screens-manage";

const NAV = [
  { group: null, items: [{ id: "overview", label: "Overview", icon: "layout-dashboard" }] },
  {
    group: "Operate",
    items: [
      { id: "providers", label: "Providers", icon: "server" },
      { id: "models", label: "Models", icon: "box" },
      { id: "routing", label: "Routing", icon: "route" },
      { id: "playground", label: "Playground", icon: "terminal" },
    ],
  },
  {
    group: "Insights",
    items: [
      { id: "usage", label: "Usage & Analytics", icon: "chart-line" },
      { id: "quota", label: "Quota & Limits", icon: "gauge" },
      { id: "token-health", label: "Token Health", icon: "heart-pulse" },
      { id: "diagnostics", label: "Diagnostics", icon: "activity" },
    ],
  },
  {
    group: "Manage",
    items: [
      { id: "api-keys", label: "API Keys", icon: "key-round" },
      { id: "settings", label: "Settings", icon: "settings" },
    ],
  },
  {
    group: "Auth & lifecycle",
    items: [
      { id: "login", label: "Owner login", icon: "lock" },
      { id: "first-run", label: "First-run setup", icon: "shield" },
      { id: "backup", label: "Backup & restore", icon: "archive" },
      { id: "tier-status", label: "Tier status", icon: "zap" },
      { id: "provider-detail", label: "Provider details", icon: "user-round" },
      { id: "routing-rules", label: "Routing rules", icon: "git-branch" },
    ],
  },
];

type ScreenComponent = React.ComponentType<{ go?: (id: string) => void }>;

const SCREENS: Record<string, ScreenComponent> = {
  overview: OperateScreens.Overview,
  providers: OperateScreens.Providers,
  "provider-detail": OperateScreens.ProviderDetail,
  models: OperateScreens.Models,
  routing: OperateScreens.Routing,
  "routing-rules": OperateScreens.RoutingRules,
  playground: OperateScreens.Playground,
  usage: InsightsScreens.Usage,
  quota: InsightsScreens.Quota,
  "token-health": InsightsScreens.TokenHealth,
  diagnostics: InsightsScreens.Diagnostics,
  "tier-status": InsightsScreens.TierStatus,
  "api-keys": ManageScreens.ApiKeys,
  settings: ManageScreens.Settings,
  login: ManageScreens.Login,
  "first-run": ManageScreens.FirstRun,
  backup: ManageScreens.Backup,
};

function Shell() {
  const [screen, setScreen] = React.useState((location.hash || "#overview").slice(1));
  const [theme, setTheme] = React.useState<ThemeName>("venom-dark");
  const [density, setDensity] = React.useState<DensityName>("comfortable");

  React.useEffect(() => {
    document.documentElement.setAttribute("data-theme", theme);
    document.documentElement.setAttribute("data-density", density);
  }, [theme, density]);

  React.useEffect(() => {
    const onHash = () => setScreen((location.hash || "#overview").slice(1));
    window.addEventListener("hashchange", onHash);
    return () => window.removeEventListener("hashchange", onHash);
  }, []);

  const Screen = SCREENS[screen] || SCREENS.overview;
  const fullBleed = screen === "login" || screen === "first-run";

  return (
    <div className="vn-shell">
      <nav className="vn-shell-nav vn-scroll" aria-label="Primary">
        <div className="vn-nav-brand">
          <Icon name="route" size={18} style={{ color: "var(--accent-default)" }} />
          Venom Router
        </div>
        {NAV.map((g, gi) => (
          <div key={gi}>
            {g.group ? <div className="vn-nav-group vn-overline">{g.group}</div> : <div style={{ height: 4 }}></div>}
            {g.items.map((it) => (
              <a
                key={it.id}
                className="vn-nav-item"
                href={"#" + it.id}
                aria-current={screen === it.id ? "page" : undefined}
                onClick={() => setScreen(it.id)}
              >
                <Icon name={it.icon} size={15} />
                {it.label}
              </a>
            ))}
          </div>
        ))}
      </nav>
      <header className="vn-shell-topbar">
        <span className="vn-badge vn-badge--healthy vn-badge--dot">All systems routing</span>
        <span className="vn-caption vn-mono-xs">127.0.0.1:8081 · loopback</span>
        <span style={{ flex: 1 }}></span>
        <ThemeSwitcher value={theme} onChange={setTheme} />
        <DensityToggle value={density} onChange={setDensity} />
        <OwnerSessionStatus state="active" idleIn="24m" absoluteIn="9h 12m" />
      </header>
      <main className="vn-shell-main vn-scroll">
        <div
          className="vn-shell-content"
          data-screen-label={screen}
          style={fullBleed ? { maxWidth: "none", padding: 0, height: "100%" } : undefined}
        >
          <Screen go={setScreen} />
        </div>
      </main>
    </div>
  );
}

const rootEl = document.getElementById("root");
if (!rootEl) throw new Error("#root not found");
createRoot(rootEl).render(<Shell />);
