// GENERATED by scripts/migrate-screens-to-vite.js from the original screens-operate.jsx — hand-edit freely, this is now a real ES module (no longer regenerated automatically).
import * as React from "react";
import { AccountIdentity, AccountStatus, AuditEventTimeline, Badge, Banner, Breadcrumbs, Button, CertificationStateBadge, CertificationTimeline, CircuitBreakerState, CodeBlock, CompetitiveBandIndicator, ContextWindowDisplay, CooldownBadge, CredentialKindBadge, DataTable, DestructiveActionConfirmation, DiagnosticEventRow, Dialog, Drawer, EmptyState, EvidenceList, FallbackChain, FilterBar, FormField, FundingBadge, FundingEvidenceIndicator, FundingMixIndicator, IconButton, Input, KeyValueList, Meter, ModelCapabilitySet, ModelIdentity, MultiWindowQuotaSummary, Panel, ProbeResultSummary, ProviderAccountRow, ProviderSummaryCard, QuotaFairnessIndicator, RadioGroup, ReauthenticationStatus, ReverificationPrompt, RoutableIndicator, SecretRevealControl, SegmentedControl, Select, StatCard, Tabs, Textarea, TierBadge, TierPolicySummary, WorkloadProfileBadge } from "../../src/index";

// ---------- 1. Overview ----------
export function Overview({ go }) {
  return (
    <React.Fragment>
      <Banner tone="warning" actions={<Button size="sm" onClick={() => go("models")}>Review queue</Button>}>
        9 offerings await certification review · grouped by reason in Models.
      </Banner>
      <div className="vn-page-header">
        <div><h1 className="vn-title-page" style={{ margin: 0 }}>Overview</h1>
          <p className="vn-page-desc">Fleet, catalog, and routing at a glance. Venom decides; the transport executes.</p></div>
        <div className="vn-page-actions"><Button variant="primary" icon="plus" onClick={() => go("providers")}>Connect provider</Button></div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "var(--space-3)" }}>
        <StatCard label="Providers" value="7" meta="of 11 configured · 1 setup required" />
        <StatCard label="Accounts" value="14" meta="12 connected · 1 cooling · 1 expired" />
        <StatCard label="Healthy accounts" value="12" meta="1 degraded" tone="healthy" />
        <StatCard label="Certified offerings" value="86" meta="of 124 discovered" />
      </div>
      <Panel title="Tier readiness">
        <div style={{ padding: "var(--space-3) var(--space-4)", display: "flex", flexDirection: "column", gap: "var(--space-2)" }}>
          {[
            { t: "lite", state: <Badge tone="healthy" icon="circle-check">eligible</Badge>, note: "9 free routes certified · headroom 64%", used: 36 },
            { t: "pro", state: <Badge tone="healthy" icon="circle-check">eligible</Badge>, note: "23 routes · paid share 22% (target 25%)", used: 58 },
            { t: "max", state: <Badge tone="degraded" icon="triangle-alert">degraded · quota constrained</Badge>, note: "band top 0.91 · 2 accounts saturated", used: 91 },
          ].map((r) => (
            <div key={r.t} style={{ display: "grid", gridTemplateColumns: "70px 220px 1fr 160px", gap: "var(--space-3)", alignItems: "center" }}>
              <TierBadge tier={r.t} />
              {r.state}
              <span className="vn-caption">{r.note}</span>
              <Meter value={r.used} max={100} label={r.t + " pooled usage"} />
            </div>
          ))}
        </div>
      </Panel>
      <Panel title="Recent diagnostics" actions={<Button size="sm" variant="ghost" onClick={() => go("diagnostics")}>Open diagnostics</Button>}>
        <div style={{ padding: "var(--space-3) var(--space-4)", display: "flex", flexDirection: "column", gap: "var(--space-2)" }}>
          <DiagnosticEventRow time="14:03:11Z" kind="route_attempt" scope="offering" code="rate_limit" detail="codex : gpt-5.2 — cooldown 41s at offering scope; fell back to claude-code" latency="1,204 ms" tone="warning" />
          <DiagnosticEventRow time="13:58:40Z" kind="probe" code="retryable_failure" detail="tools probe on glm-5-free — capability truth unchanged, retry in 4m" tone="info" />
          <DiagnosticEventRow time="13:41:02Z" kind="reconciliation" code="usage_gap" detail="req_01J9YH… reached unknown_consumption — re-baseline at next sync" tone="critical" />
        </div>
      </Panel>
    </React.Fragment>
  );
};

// ---------- 2. Providers ----------
export function Providers({ go }) {
  const [dlg, setDlg] = React.useState(false);
  const [funding, setFunding] = React.useState("free");
  const [filter, setFilter] = React.useState("Active");
  const [q, setQ] = React.useState("");
  return (
    <React.Fragment>
      <div className="vn-page-header">
        <div><h1 className="vn-title-page" style={{ margin: 0 }}>Providers</h1>
          <p className="vn-page-desc">The integration fleet. Funding is a fact about each account — never about a provider.</p></div>
        <div className="vn-page-actions"><Button variant="primary" icon="plus" onClick={() => setDlg(true)}>Connect provider</Button></div>
      </div>
      <FilterBar searchValue={q} onSearchChange={setQ} searchPlaceholder="Filter providers and accounts">
        <SegmentedControl label="Show" options={["Active", "All integrations"]} value={filter} onChange={setFilter} />
      </FilterBar>
      <ProviderSummaryCard name="Claude Code" slug="claude-code" authMode="oauth2" accountCount={2} healthyCount={1} verification="proven"
        actions={<IconButton icon="plus" label="Connect another account" variant="secondary" />}>
        <ProviderAccountRow
          identity={<AccountIdentity name="ops@venom.local" externalId="acct_9f2e11c4" plan="Max" />}
          status={<AccountStatus status="healthy" />}
          funding={<FundingBadge funding="paid" plan="Max" source="provider_evidence" />}
          quota={<div style={{ width: 140 }}><Meter value={61} max={100} label="5-hour window" /></div>}
          actions={<IconButton icon="ellipsis" label="Account actions" size="sm" onClick={() => go("provider-detail")} />} />
        <ProviderAccountRow
          identity={<AccountIdentity name="lab@venom.local" externalId="acct_77aa02b9" plan="Pro" />}
          status={<AccountStatus status="cooling_down" retryAfter="4m 12s" />}
          funding={<FundingBadge funding="paid" plan="Pro" source="provider_evidence" />}
          quota={<div style={{ width: 140 }}><Meter value={97} max={100} label="7-day window" /></div>}
          actions={<IconButton icon="ellipsis" label="Account actions" size="sm" />} />
      </ProviderSummaryCard>
      <ProviderSummaryCard name="OpenCode Zen" slug="opencode-zen" authMode="api_key" accountCount={3} healthyCount={3} verification="proven"
        actions={<IconButton icon="plus" label="Connect another account" variant="secondary" />}>
        <ProviderAccountRow
          identity={<AccountIdentity name="key_9c41…f2" externalId="key_9c41e8b0f2" plan="Free" />}
          status={<AccountStatus status="healthy" />}
          funding={<FundingBadge funding="free" source="owner_policy" />}
          quota={<div style={{ width: 140 }}><Meter unknown label="Provider quota" /></div>}
          actions={<IconButton icon="ellipsis" label="Account actions" size="sm" />} />
      </ProviderSummaryCard>
      <ProviderSummaryCard name="Antigravity" slug="antigravity" authMode="oauth2" accountCount={0} verification="proven"
        setupRequired missingEnv={["VENOM_ANTIGRAVITY_CLIENT_SECRET", "VENOM_ANTIGRAVITY_CLIENT_ID"]} />
      <ProviderSummaryCard name="Agnes AI" slug="agnes-ai" authMode="api_key" accountCount={0} verification="partial"
        actions={<Button size="sm" icon="plus" onClick={() => setDlg(true)}>Connect</Button>}>
        <EmptyState icon="user-round" title="No accounts connected" description="Agnes AI cannot be classified from its catalog (evidence required): new accounts start with unknown funding and stay out of routing until classified." />
      </ProviderSummaryCard>
      <Dialog open={dlg} onClose={() => setDlg(false)} title="Connect OpenCode Zen account"
        footer={<React.Fragment><Button onClick={() => setDlg(false)}>Cancel</Button><Button variant="primary" onClick={() => setDlg(false)}>Validate & connect</Button></React.Fragment>}>
        <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
          <FormField label="API key" required description="Validated authentically with a zero-cost chat probe. 429/5xx means provider-unavailable (retryable), not an invalid key.">
            <Input mono placeholder="Paste the provider API key" />
          </FormField>
          <FormField label="Funding classification" description="Recorded as owner evidence. Unknown keeps the account out of all routing until classified.">
            <RadioGroup name="fund" value={funding} onChange={setFunding} options={[
              { value: "free", label: "Free — verified zero marginal cost" },
              { value: "paid", label: "Paid" },
              { value: "unknown", label: "Unknown — classify later" },
            ]} />
          </FormField>
        </div>
      </Dialog>
    </React.Fragment>
  );
};

// ---------- 3. Provider details ----------
export function ProviderDetail({ go }) {
  const [tab, setTab] = React.useState("credentials");
  const [reverify, setReverify] = React.useState(false);
  const [revealed, setRevealed] = React.useState(false);
  const [disc, setDisc] = React.useState(false);
  return (
    <React.Fragment>
      <Breadcrumbs items={[{ label: "Providers", href: "#providers" }, { label: "claude-code", href: "#providers" }, { label: "ops@venom.local" }]} />
      <div className="vn-page-header">
        <div>
          <h1 className="vn-title-page" style={{ margin: 0, display: "flex", gap: "var(--space-3)", alignItems: "center" }}>
            ops@venom.local <AccountStatus status="healthy" />
          </h1>
          <p className="vn-page-desc">claude-code · OAuth · external ID <span className="vn-code-inline">acct_9f2e11c4</span></p>
        </div>
        <div className="vn-page-actions">
          <Button icon="refresh-cw">Refresh</Button>
          <Button icon="fingerprint">Reauthenticate</Button>
          <Button variant="danger" icon="unplug" onClick={() => setDisc(true)}>Disconnect</Button>
        </div>
      </div>
      <Tabs label="Account detail" value={tab} onChange={setTab} tabs={[
        { value: "credentials", label: "Credentials" }, { value: "funding", label: "Funding" },
        { value: "quota", label: "Quota", count: 4 }, { value: "audit", label: "Audit" },
      ]} />
      {tab === "credentials" && (
        <Panel title="Credentials (one active per kind)">
          <div style={{ padding: "var(--space-3) var(--space-4)", display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
            <div style={{ display: "flex", gap: "var(--space-2)", alignItems: "center", flexWrap: "wrap" }}>
              <CredentialKindBadge kind="oauth2" expiresAt="54m" />
              <SecretRevealControl masked="sk-ant-oat••••••••••••" secret="sk-ant-oat-EXAMPLE-FIXTURE-not-real" revealed={revealed}
                blocked={!revealed} onRevealRequest={() => setReverify(true)} onHide={() => setRevealed(false)} label="OAuth credential" />
              <ReauthenticationStatus state="idle" />
            </div>
            <KeyValueList items={[
              { key: "Fingerprint", value: "sha256:9c41…88e2", mono: true },
              { key: "Keyring version", value: "key_v2", mono: true },
              { key: "Expires", value: "2026-07-22 15:02Z (auto-refresh)", mono: true },
            ]} />
          </div>
        </Panel>
      )}
      {tab === "funding" && (
        <Panel title="Funding evidence (append-only, one current row)">
          <div style={{ padding: "var(--space-3) var(--space-4)", display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
            <FundingEvidenceIndicator funding="paid" source="provider_evidence" confidence={0.95} observedAt="2026-07-22 09:14Z" />
            <span className="vn-caption">Provider plan string "Max" mapped to paid (0.95). An owner override would supersede this row and is never auto-superseded back.</span>
            <Button icon="user-round" size="sm" style={{ alignSelf: "flex-start" }}>Override funding…</Button>
          </div>
        </Panel>
      )}
      {tab === "quota" && (
        <Panel title="Quota windows (most restrictive governs)">
          <div style={{ padding: "var(--space-3) var(--space-4)" }}>
            <MultiWindowQuotaSummary windows={[
              { windowKey: "provider:five_hour", used: 61, total: 100, unit: "%", state: "available", freshness: "fresh" },
              { windowKey: "provider:seven_day", used: 97, total: 100, unit: "%", state: "insufficient", freshness: "stale", age: "22m" },
              { windowKey: "local:concurrency", used: 0, total: 2, unit: "in-flight", state: "available", freshness: "fresh" },
              { windowKey: "local:requests", used: 140, total: 500, unit: "req", state: "available", freshness: "fresh" },
            ]} />
          </div>
        </Panel>
      )}
      {tab === "audit" && (
        <Panel title="Audit trail (ids and codes only — never secrets)">
          <div style={{ padding: "var(--space-3) var(--space-4)" }}>
            <AuditEventTimeline events={[
              { action: "credential_reveal", summary: "Owner revealed OAuth credential (re-verified 14:01:12Z)", at: "2026-07-22 14:01:55Z", tone: "warning" },
              { action: "quota_sync", summary: "2 provider windows re-baselined", at: "2026-07-22 13:40:00Z" },
              { action: "reauthentication", summary: "Staged credential activated; previous retired + revoked", at: "2026-07-20 08:12:31Z", tone: "accent" },
            ]} />
          </div>
        </Panel>
      )}
      <ReverificationPrompt open={reverify} action="reveal this credential"
        onConfirm={() => { setReverify(false); setRevealed(true); }} onCancel={() => setReverify(false)} />
      <DestructiveActionConfirmation open={disc} title="Disconnect ops@venom.local?"
        consequence="Routing through this account stops immediately and its credentials are retired (revoked where possible). Sanitized history and audit records are retained. Reconnecting requires a new enrollment — this is V1's soft disconnect, not a purge."
        confirmWord="disconnect" confirmLabel="Disconnect account" onConfirm={() => setDisc(false)} onCancel={() => setDisc(false)} />
    </React.Fragment>
  );
};

// ---------- 4. Models ----------
export function Models() {
  const [row, setRow] = React.useState(null);
  const [view, setView] = React.useState("All");
  const [q, setQ] = React.useState("");
  const rows = [
    { id: 1, name: "Claude Sonnet 4.5", pid: "claude-sonnet-4-5-20250929", provider: "claude-code", account: "ops@venom.local", ctx: 1000000, verified: true, cert: "certified", truths: { chat: "supported", streaming: "supported", tools: "supported", structured_output: "supported", vision: "supported" }, funding: "paid" },
    { id: 2, name: "GPT-5.2 Codex", pid: "gpt-5.2-codex", provider: "codex", account: "dev@venom.local", ctx: 400000, verified: true, cert: "certified", truths: { chat: "supported", streaming: "supported", tools: "supported", structured_output: "unknown", vision: "supported" }, funding: "paid" },
    { id: 3, name: "GLM-5 Free", pid: "glm-5-free", provider: "opencode-zen", account: "key_9c41…f2", ctx: 262144, verified: false, cert: "probing", truths: { chat: "supported", streaming: "supported", tools: "unknown", structured_output: "unknown", vision: "unsupported" }, funding: "free" },
    { id: 4, name: "Kimi K2.5", pid: "kimi-k2.5", provider: "agnes-ai", account: "key_11ab…9d", ctx: null, verified: false, cert: "observed", truths: { chat: "unknown" }, funding: "unknown" },
  ];
  const sel = rows.find((r) => r.id === (row && row.id));
  return (
    <React.Fragment>
      <div className="vn-page-header">
        <div><h1 className="vn-title-page" style={{ margin: 0 }}>Models</h1>
          <p className="vn-page-desc">Account-scoped offerings with certification and capability truth. Nothing here is hardcoded — every fact carries provenance.</p></div>
        <div className="vn-page-actions"><Button icon="box">Run discovery</Button></div>
      </div>
      <FilterBar searchValue={q} onSearchChange={setQ} searchPlaceholder="Filter by model, provider, account">
        <SegmentedControl label="View" options={["All", "Routable", "Review queue"]} value={view} onChange={setView} />
        <span className="vn-caption">124 offerings · 86 routable · 9 in review</span>
      </FilterBar>
      <DataTable label="Offerings" rowKey="id" rows={rows} onRowClick={setRow} selectedKey={sel && sel.id}
        columns={[
          { key: "name", label: "Offering", render: (r) => <ModelIdentity name={r.name} providerModelId={r.pid} /> },
          { key: "provider", label: "Provider · account", mono: true, render: (r) => r.provider + " · " + r.account },
          { key: "ctx", label: "Context", numeric: true, render: (r) => <ContextWindowDisplay tokens={r.ctx} verified={r.verified} /> },
          { key: "caps", label: "Capability truth", render: (r) => <ModelCapabilitySet showLabels={false} truths={r.truths} /> },
          { key: "cert", label: "Certification", render: (r) => <CertificationStateBadge state={r.cert} /> },
          { key: "funding", label: "Funding", render: (r) => <Badge tone={r.funding === "free" ? "healthy" : r.funding === "paid" ? "info" : "unknown"} icon={r.funding === "free" ? "hand-coins" : r.funding === "paid" ? "credit-card" : "circle-help"}>{r.funding}</Badge> },
        ]}
        empty={<EmptyState icon="box" title="No offerings discovered" description="Run discovery on a connected account." />} />
      <Drawer open={!!sel} onClose={() => setRow(null)} title={sel ? sel.name : ""} wide
        footer={<React.Fragment><Button icon="flask-conical">Run probes</Button><Button variant="primary">Open certification</Button></React.Fragment>}>
        {sel && (
          <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-4)" }}>
            <RoutableIndicator state={sel.cert} truths={sel.truths} required={["chat", "tools"]} />
            <CertificationTimeline state={sel.cert} />
            <ModelCapabilitySet truths={sel.truths} />
            <ProbeResultSummary operation="tools" execution={sel.cert === "probing" ? "retryable_failure" : "succeeded"} truth={sel.truths.tools || "unknown"} note={sel.cert === "probing" ? "429 during probe — truth unchanged, retry with backoff" : "fixture probe verdict"} at="13:58:40Z" />
            <EvidenceList items={[
              { field: "context_length", value: sel.ctx ? sel.ctx.toLocaleString() : null, mono: true, source: sel.verified ? "probe" : "provider_discovery", confidence: sel.verified ? 0.98 : 0.5, observedAt: "2026-07-22" },
              { field: "cost.input", value: sel.funding === "free" ? "0 (verified)" : sel.funding === "paid" ? "known" : null, source: sel.funding === "unknown" ? "models_dev" : "provider_price", confidence: sel.funding === "unknown" ? 0.3 : 0.9, exactMatch: sel.funding !== "unknown", observedAt: "2026-07-22" },
            ]} />
          </div>
        )}
      </Drawer>
    </React.Fragment>
  );
};

// ---------- 5. Routing (tier profiles) ----------
export function Routing({ go }) {
  return (
    <React.Fragment>
      <div className="vn-page-header">
        <div><h1 className="vn-title-page" style={{ margin: 0 }}>Routing</h1>
          <p className="vn-page-desc">Three products, one capability surface. Tiers differ only in quality, context ceiling, thinking budget, and funding policy.</p></div>
        <div className="vn-page-actions"><Button icon="git-branch" onClick={() => go("routing-rules")}>Rules & fallback</Button><Button icon="zap" onClick={() => go("tier-status")}>Tier status</Button></div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "var(--space-3)" }}>
        <TierPolicySummary tier="lite" />
        <TierPolicySummary tier="pro" />
        <TierPolicySummary tier="max" />
      </div>
      <p className="vn-caption">Public model IDs: <span className="vn-code-inline">venom/lite</span> <span className="vn-code-inline">venom/pro</span> <span className="vn-code-inline">venom/max</span> — the only three; requests above a tier's context ceiling are rejected with <span className="vn-code-inline">venom_context_exceeds_tier</span>, never silently promoted.</p>
    </React.Fragment>
  );
};

// ---------- 6. Routing rules & fallback ----------
export function RoutingRules() {
  return (
    <React.Fragment>
      <div className="vn-page-header">
        <div><h1 className="vn-title-page" style={{ margin: 0 }}>Routing rules & fallback</h1>
          <p className="vn-page-desc">Hard gates → route groups → weighted score → competitive band → per-tier distribution → capacity-fair account pick.</p></div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "var(--space-3)" }}>
        <Panel title="Competitive band (never auto-widened)">
          <div style={{ padding: "var(--space-3) var(--space-4)" }}>
            <CompetitiveBandIndicator tier="pro" top={0.91} candidates={[
              { name: "sonnet-4-5", quality: 0.91 }, { name: "glm-5", quality: 0.88 }, { name: "gpt-5.2", quality: 0.79 }]} />
          </div>
        </Panel>
        <Panel title="Fallback (scope-classified, bounded)">
          <div style={{ padding: "var(--space-3) var(--space-4)" }}>
            <FallbackChain budget={4} attempts={[
              { route: "codex : gpt-5.2", outcome: "failed", code: "rate_limit" },
              { route: "opencode-zen : glm-5", outcome: "skipped", code: "cooling_down" },
              { route: "claude-code : sonnet-4-5", outcome: "succeeded" }]} />
          </div>
        </Panel>
        <Panel title="Pro funding mix (per workload bucket)">
          <div style={{ padding: "var(--space-3) var(--space-4)", display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
            <FundingMixIndicator paidShare={0.22} bucket="standard" sample={2000} />
            <FundingMixIndicator paidShare={0.29} bucket="structured+vision" sample={412} />
            <span className="vn-caption">Deficit cells are per (tier, workload bucket, funding class) — a vision burst never distorts text accounting.</span>
          </div>
        </Panel>
        <Panel title="Max quota fairness (no funding-mix target)">
          <div style={{ padding: "var(--space-3) var(--space-4)" }}>
            <QuotaFairnessIndicator accounts={[
              { name: "ops@venom.local", weight: 0.5, realized: 0.47 },
              { name: "lab@venom.local", weight: 0.3, realized: 0.34 },
              { name: "dev@venom.local", weight: 0.2, realized: 0.19, saturated: true }]} />
          </div>
        </Panel>
      </div>
      <div className="vn-toolbar">
        <CircuitBreakerState state="open" scope="provider:codex" reopensIn="3m 12s" cycle={2} />
        <CircuitBreakerState state="half_open" scope="offering:glm-5" />
        <CooldownBadge scope="account" retryAfter="41s" />
        <span className="vn-toolbar-spacer"></span>
        <WorkloadProfileBadge properties={["vision", "structured"]} />
      </div>
    </React.Fragment>
  );
};

// ---------- 7. Playground ----------
export function Playground() {
  const [tier, setTier] = React.useState("venom/max");
  return (
    <React.Fragment>
      <div className="vn-page-header">
        <div><h1 className="vn-title-page" style={{ margin: 0 }}>Playground</h1>
          <p className="vn-page-desc">Exercise the public surface with the optional <span className="vn-code-inline">venom</span> extension. Responses expose the chosen route via X-Venom-* headers.</p></div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "380px 1fr", gap: "var(--space-4)", alignItems: "start" }}>
        <div className="vn-panel" style={{ padding: "var(--space-4)", display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
          <FormField label="Model (tier)"><Select options={["venom/lite", "venom/pro", "venom/max"]} value={tier} onChange={(e) => setTier(e.target.value)} /></FormField>
          <FormField label="Thinking budget" description="Above the tier ceiling clamps and is reported — asking for ultra on Pro yields extended.">
            <Select options={["none", "standard", "extended", "ultra"]} defaultValue="extended" />
          </FormField>
          <FormField label="Required capabilities" description="Become hard routing gates (Step 3).">
            <Select options={["(none)", "reasoning", "vision", "tools", "reasoning + vision"]} defaultValue="(none)" />
          </FormField>
          <FormField label="Prompt"><Textarea rows={5} placeholder="Ask something…" /></FormField>
          <Button variant="primary" icon="play">Send</Button>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
          <div className="vn-panel" style={{ padding: "var(--space-4)" }}>
            <div style={{ display: "flex", gap: "var(--space-2)", alignItems: "center", marginBottom: "var(--space-3)", flexWrap: "wrap" }}>
              <TierBadge tier="max" />
              <Badge tone="inactive" mono>claude-code</Badge>
              <Badge tone="inactive" mono>claude-sonnet-4-5</Badge>
              <Badge tone="info" icon="credit-card">paid</Badge>
              <Badge tone="inactive" icon="timer" mono>1,204 ms</Badge>
              <Badge tone="inactive" icon="corner-down-right" mono>1 fallback</Badge>
            </div>
            <p className="vn-body" style={{ margin: 0 }}>Here is the summary you asked for — the reservation settled at 1,912 output tokens…</p>
          </div>
          <CodeBlock label="Response telemetry headers" code={'X-Venom-Request-Id: req_01J9ZK4T7Q\nX-Venom-Tier: max\nX-Venom-Provider: claude-code\nX-Venom-Model: claude-sonnet-4-5\nX-Venom-Funding: paid\nX-Venom-Latency-Ms: 1204\nX-Venom-Tokens-In: 5211\nX-Venom-Tokens-Out: 1912\nX-Venom-Fallback-Attempts: 1'} />
          <KeyValueList items={[{ key: "Clamp", value: "none (ultra allowed on max)" }, { key: "Stickiness", value: "pin recorded on success · TTL 15m", mono: true }]} />
        </div>
      </div>
    </React.Fragment>
  );
};
