// GENERATED by scripts/migrate-screens-to-vite.js from the original screens-manage.jsx — hand-edit freely, this is now a real ES module (no longer regenerated automatically).
import * as React from "react";
import { APIKeyCreationResult, APIKeyPrefix, Alert, BackupStatus, Badge, Button, DataTable, DestructiveActionConfirmation, Dialog, FormField, Input, JobProgress, KeyValueList, OwnerSessionStatus, Panel, RestoreStatus, Select, Slider, Stepper, Switch, TypedErrorDisplay } from "../../src/index";

// ---------- 12. API keys ----------
export function ApiKeys() {
  const [create, setCreate] = React.useState(false);
  const [result, setResult] = React.useState(false);
  const [revoke, setRevoke] = React.useState(false);
  const rows = [
    { id: 1, label: "ide-clients", prefix: "vk_live_3f8a", rpm: 120, created: "2026-06-30", last: "2m ago" },
    { id: 2, label: "home-server", prefix: "vk_live_88c1", rpm: 60, created: "2026-05-12", last: "3d ago" },
  ];
  return (
    <React.Fragment>
      <div className="vn-page-header">
        <div><h1 className="vn-title-page" style={{ margin: 0 }}>API keys</h1>
          <p className="vn-page-desc">Venom keys authorize inference. Raw keys are shown once at creation; only a hash is stored.</p></div>
        <div className="vn-page-actions"><Button variant="primary" icon="plus" onClick={() => setCreate(true)}>Create key</Button></div>
      </div>
      {result ? <APIKeyCreationResult rawKey="vk_live_3f8a-EXAMPLE-FIXTURE-0000-not-real" keyLabel="ide-clients" onDone={() => setResult(false)} /> : null}
      <DataTable label="API keys" rowKey="id" rows={rows}
        columns={[
          { key: "label", label: "Label" },
          { key: "prefix", label: "Key", render: (r) => <APIKeyPrefix prefix={r.prefix} /> },
          { key: "rpm", label: "RPM limit", numeric: true },
          { key: "created", label: "Created", mono: true },
          { key: "last", label: "Last used", mono: true },
          { key: "act", label: "", render: () => <Button size="sm" variant="danger" icon="trash-2" onClick={() => setRevoke(true)}>Revoke</Button> },
        ]} />
      <Dialog open={create} onClose={() => setCreate(false)} title="Create API key"
        footer={<React.Fragment><Button onClick={() => setCreate(false)}>Cancel</Button><Button variant="primary" onClick={() => { setCreate(false); setResult(true); }}>Create</Button></React.Fragment>}>
        <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
          <FormField label="Label" required><Input placeholder="e.g. ide-clients" /></FormField>
          <FormField label="Per-key RPM limit" description="Ingress rate limiting for this key."><Slider min={10} max={600} step={10} defaultValue={120} unit=" rpm" label="RPM limit" /></FormField>
        </div>
      </Dialog>
      <DestructiveActionConfirmation open={revoke} title="Revoke ide-clients?"
        consequence="Clients holding this key lose access immediately. The key cannot be re-enabled — create a new one instead."
        confirmLabel="Revoke key" onConfirm={() => setRevoke(false)} onCancel={() => setRevoke(false)} />
    </React.Fragment>
  );
};

// ---------- 13. Settings ----------
export function Settings() {
  return (
    <React.Fragment>
      <div className="vn-page-header">
        <div><h1 className="vn-title-page" style={{ margin: 0 }}>Settings</h1>
          <p className="vn-page-desc">Owner policy. Theme and density persist server-side; probe caps and staleness windows are bounded-validated.</p></div>
        <div className="vn-page-actions"><Button variant="primary">Save changes</Button></div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "var(--space-3)", alignItems: "start" }}>
        <Panel title="Appearance">
          <div style={{ padding: "var(--space-3) var(--space-4)", display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
            <FormField label="Theme" description="Stored via PUT /settings — applied before first paint."><Select options={["venom-dark (default)", "venom-light"]} defaultValue="venom-dark (default)" /></FormField>
            <FormField label="Density"><Select options={["comfortable", "compact"]} defaultValue="comfortable" /></FormField>
          </div>
        </Panel>
        <Panel title="Intelligence & probes">
          <div style={{ padding: "var(--space-3) var(--space-4)", display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
            <Switch label="Metadata enrichment (models.dev + quality signals) — off by default; never weakens free-safety" />
            <Switch label="Expensive probes (opt-in)" />
            <FormField label="Probe cost cap per account" description="Hard cap; probes are quota-protected (1 in-flight per provider).">
              <Slider min={0} max={50} defaultValue={10} unit=" req/day" label="Probe cap" />
            </FormField>
            <FormField label="Quota staleness threshold"><Slider min={5} max={60} defaultValue={15} unit=" min" label="Staleness" /></FormField>
            <FormField label="Free-safety staleness window" description="Beyond this, unverifiable cost resolves to unknown (fail closed).">
              <Slider min={1} max={72} defaultValue={24} unit=" h" label="Free-safety window" />
            </FormField>
          </div>
        </Panel>
        <Panel title="Binds (control plane is loopback-only)">
          <div style={{ padding: "var(--space-3) var(--space-4)", display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
            <FormField label="Control plane" description="Fixed to loopback in V1 — no opt-out."><Input mono value="127.0.0.1:8081" readOnly /></FormField>
            <FormField label="Inference bind" description="May differ; still requires a vk_live_* key."><Input mono defaultValue="127.0.0.1:8081" /></FormField>
          </div>
        </Panel>
        <Panel title="Owner password">
          <div style={{ padding: "var(--space-3) var(--space-4)", display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
            <FormField label="Current password"><Input type="password" autoComplete="current-password" /></FormField>
            <FormField label="New password" description="Argon2id, hash-only. Changing it revokes all sessions."><Input type="password" autoComplete="new-password" /></FormField>
            <Badge tone="info" icon="info">Lost password? Restore from an encrypted backup, or run the documented local reset (returns to first-run setup; encrypted credentials stay sealed).</Badge>
          </div>
        </Panel>
      </div>
    </React.Fragment>
  );
};

// ---------- 14. Owner login ----------
export function Login({ go }) {
  const [failed, setFailed] = React.useState(false);
  return (
    <div style={{ display: "grid", placeItems: "center", height: "100%", background: "var(--surface-canvas)" }} data-screen-label="login">
      <div style={{ width: 380, display: "flex", flexDirection: "column", gap: "var(--space-4)" }}>
        <div style={{ textAlign: "center" }}>
          <div className="vn-display" style={{ marginBottom: 4 }}>Venom Router</div>
          <div className="vn-caption">Owner console · 127.0.0.1:8081 · single owner, no accounts to pick</div>
        </div>
        <div className="vn-card vn-card--pad" style={{ display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
          <FormField label="Owner password"><Input type="password" autoComplete="current-password" /></FormField>
          {failed ? <TypedErrorDisplay code="invalid_credentials" retryable message="The password is incorrect. Repeated failures are rate-limited." /> : null}
          <Button variant="primary" icon="lock" onClick={() => setFailed(!failed)}>Sign in</Button>
          <span className="vn-caption" style={{ textAlign: "center" }}>Sessions: 30 min idle · 12 h absolute. Lost password → restore a backup or run the local reset.</span>
        </div>
        <div style={{ textAlign: "center" }}><OwnerSessionStatus state="unauthenticated" /></div>
      </div>
    </div>
  );
};

// ---------- 15. First-run setup ----------
export function FirstRun({ go }) {
  return (
    <div style={{ display: "grid", placeItems: "center", height: "100%", background: "var(--surface-canvas)" }} data-screen-label="first-run">
      <div style={{ width: 440, display: "flex", flexDirection: "column", gap: "var(--space-4)" }}>
        <div style={{ textAlign: "center" }}>
          <div className="vn-display" style={{ marginBottom: 4 }}>Welcome to Venom Router</div>
          <div className="vn-caption">First run — create the single owner password. There are no users, roles, or teams.</div>
        </div>
        <Stepper steps={["Create password", "Sign in", "Connect a provider"]} current={0} />
        <div className="vn-card vn-card--pad" style={{ display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
          <FormField label="Owner password" required description="Stored as an Argon2id hash only — the password itself is never written anywhere.">
            <Input type="password" autoComplete="new-password" />
          </FormField>
          <FormField label="Confirm password"><Input type="password" autoComplete="new-password" /></FormField>
          <Alert tone="info" title="No recovery email exists.">If you lose this password, recovery is a backup restore or the documented local reset. Consider creating an encrypted backup once set up.</Alert>
          <Button variant="primary" icon="shield" onClick={() => go("login")}>Create password & continue</Button>
        </div>
      </div>
    </div>
  );
};

// ---------- 16. Backup & restore ----------
export function Backup() {
  const [running, setRunning] = React.useState(false);
  return (
    <React.Fragment>
      <div className="vn-page-header">
        <div><h1 className="vn-title-page" style={{ margin: 0 }}>Backup & restore</h1>
          <p className="vn-page-desc">One encrypted container (Argon2id + AEAD) — never a raw database + keyring pair. Restore validates fully before an atomic swap; failure leaves live state untouched.</p></div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "var(--space-3)", alignItems: "start" }}>
        <Panel title="Create backup">
          <div style={{ padding: "var(--space-3) var(--space-4)", display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
            <FormField label="Backup passphrase" required description="Independent of the owner login password.">
              <Input type="password" autoComplete="new-password" />
            </FormField>
            <Alert tone="warning" title="Without your passphrase, this backup cannot be restored.">The passphrase is never stored or logged.</Alert>
            <Button variant="primary" icon="archive" onClick={() => setRunning(true)}>Create encrypted backup</Button>
            {running ? <JobProgress state="running" kind="backup" jobId="job_9310" detail="Consistent SQLite snapshot → Argon2id key → AEAD container" /> : <BackupStatus state="completed" artifact="venom-2026-07-22.vbk" at="2026-07-22 09:14Z" />}
          </div>
        </Panel>
        <Panel title="Restore from container">
          <div style={{ padding: "var(--space-3) var(--space-4)", display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
            <FormField label="Container file"><Input mono placeholder="venom-2026-07-22.vbk" /></FormField>
            <FormField label="Backup passphrase"><Input type="password" /></FormField>
            <Stepper steps={["Validate", "Decrypt", "Verify", "Swap"]} current={2} />
            <RestoreStatus state="verifying" />
            <KeyValueList items={[
              { key: "Integrity", value: "PRAGMA integrity_check · manifest hash", mono: true },
              { key: "Owner password", value: "Re-established from the container (supported recovery path)" },
              { key: "On failure", value: "Live state untouched · temp dir cleaned" },
            ]} />
            <Button icon="archive-restore">Restore</Button>
          </div>
        </Panel>
      </div>
    </React.Fragment>
  );
};
