// GENERATED by scripts/migrate-screens-to-vite.js from the original screens-insights.jsx — hand-edit freely, this is now a real ES module (no longer regenerated automatically).
import * as React from "react";
import { AccountStatus, Badge, Button, CandidateRejectionReason, CredentialKindBadge, DataTable, Drawer, FilterBar, LocalSafetyBudgetIndicator, Meter, Panel, QuotaUnknownState, QuotaWindowCard, RawPayloadDisclosure, ReauthenticationStatus, ReconciliationStatus, RouteDecisionTrace, RoutingAttemptTimeline, SegmentedControl, Select, StatCard, TierBadge, TraceId, TypedErrorDisplay } from "../../src/index";

// ---------- 8. Usage & analytics ----------
export function Usage() {
  const [range, setRange] = React.useState("7d");
  const rows = [
    { id: 1, route: "claude-code · ops@venom.local", model: "claude-sonnet-4-5", tier: "max", req: 1204, tin: 8113940, tout: 942115, p95: "1,204 ms", funding: "paid" },
    { id: 2, route: "opencode-zen · key_9c41…f2", model: "glm-5-free", tier: "lite", req: 3811, tin: 2401552, tout: 511208, p95: "612 ms", funding: "free" },
    { id: 3, route: "codex · dev@venom.local", model: "gpt-5.2-codex", tier: "pro", req: 987, tin: 903118, tout: 220043, p95: "1,038 ms", funding: "paid" },
    { id: 4, route: "xai · grok@venom.local", model: "grok-4-fast", tier: "pro", req: 640, tin: 512400, tout: 98770, p95: "488 ms", funding: "free" },
  ];
  return (
    <React.Fragment>
      <div className="vn-page-header">
        <div><h1 className="vn-title-page" style={{ margin: 0 }}>Usage & analytics</h1>
          <p className="vn-page-desc">Consumption per account, model, and tier — usage is recorded on every terminal path, never swallowed.</p></div>
        <div className="vn-page-actions"><SegmentedControl label="Range" options={["24h", "7d", "30d"]} value={range} onChange={setRange} /></div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "var(--space-3)" }}>
        <StatCard label="Requests" value="6,642" meta="98.9% routed · 0.4% failed closed" />
        <StatCard label="Tokens in / out" value="11.9M / 1.77M" meta="tabular, per terminal path" />
        <StatCard label="Paid share (Pro)" value="22%" meta="target 25% · within ±5pp" />
        <StatCard label="p95 routing overhead" value="14 ms" meta="decision + reservation only" />
      </div>
      <DataTable label="Usage by route" rowKey="id" rows={rows}
        columns={[
          { key: "route", label: "Provider · account", mono: true },
          { key: "model", label: "Model", mono: true },
          { key: "tier", label: "Tier", render: (r) => <TierBadge tier={r.tier} /> },
          { key: "req", label: "Requests", numeric: true, sortable: true, render: (r) => r.req.toLocaleString() },
          { key: "tin", label: "Tokens in", numeric: true, render: (r) => r.tin.toLocaleString() },
          { key: "tout", label: "Tokens out", numeric: true, render: (r) => r.tout.toLocaleString() },
          { key: "p95", label: "p95 latency", numeric: true },
          { key: "funding", label: "Funding", render: (r) => <Badge tone={r.funding === "free" ? "healthy" : "info"} icon={r.funding === "free" ? "hand-coins" : "credit-card"}>{r.funding}</Badge> },
        ]} />
    </React.Fragment>
  );
};

// ---------- 9. Quota & limits ----------
export function Quota() {
  return (
    <React.Fragment>
      <div className="vn-page-header">
        <div><h1 className="vn-title-page" style={{ margin: 0 }}>Quota & limits</h1>
          <p className="vn-page-desc">Multiple concurrent windows per account in provider-native units. Unknown is never unlimited — the local safety budget always bounds execution.</p></div>
        <div className="vn-page-actions"><Button icon="refresh-cw">Sync quota</Button></div>
      </div>
      <div className="vn-toolbar">
        <div style={{ width: 280 }}><Select aria-label="Account" options={["claude-code · ops@venom.local", "opencode-zen · key_9c41…f2", "codex · dev@venom.local"]} defaultValue="claude-code · ops@venom.local" /></div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "var(--space-3)" }}>
        <QuotaWindowCard name="5-hour usage" windowKey="provider:five_hour" used={61} total={100} reserved={6} unit="%" resetIn="2h 14m" freshness="fresh" />
        <QuotaWindowCard name="7-day usage" windowKey="provider:seven_day" used={97} total={100} unit="%" state="insufficient" resetIn="2d 6h" freshness="stale" age="22m" />
        <QuotaWindowCard name="Requests / minute" windowKey="rolling:60s" used={12} total={60} unit="req" resetIn="31s" freshness="fresh" />
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "var(--space-3)" }}>
        <LocalSafetyBudgetIndicator concurrencyUsed={1} concurrencyCap={2} consumptionUsed={140} consumptionCap={500} consumptionUnit="requests" />
        <QuotaUnknownState note="opencode-zen exposes no quota endpoint. Eligibility is unaffected for Lite (free-verified), but every execution still reserves against local-safety windows." />
      </div>
      <Panel title="Reconciliation queue (owner recovery)">
        <div style={{ padding: "var(--space-3) var(--space-4)", display: "flex", flexDirection: "column", gap: "var(--space-2)" }}>
          <ReconciliationStatus state="reconciliation_pending" attemptId="req_01J9ZK4T7Q · attempt 2" windows={["provider:five_hour", "local:concurrency"]} attempts="3/5" nextRetry="28m" onResync={() => {}} onAcceptEstimate={() => {}} />
          <ReconciliationStatus state="unknown_consumption" attemptId="req_01J9YH2M8P · attempt 1" windows={["provider:balance"]} onResync={() => {}} />
        </div>
      </Panel>
    </React.Fragment>
  );
};

// ---------- 10. Token health ----------
export function TokenHealth() {
  const rows = [
    { id: 1, account: "claude-code · ops@venom.local", kind: "oauth2", exp: "54m (auto-refresh)", status: "healthy", reauth: "idle" },
    { id: 2, account: "github-copilot · ci@venom.local", kind: "copilot_service", exp: "24m", status: "healthy", reauth: "idle" },
    { id: 3, account: "codex · dev@venom.local", kind: "oauth2", exp: "expired 2h ago", status: "expired", reauth: "staged" },
    { id: 4, account: "xai · grok@venom.local", kind: "oauth2", exp: "rotating (single-use refresh)", status: "reauthenticating", reauth: "validating" },
    { id: 5, account: "opencode-zen · key_9c41…f2", kind: "api_key", exp: "no expiry", status: "healthy", reauth: "idle" },
  ];
  return (
    <React.Fragment>
      <div className="vn-page-header">
        <div><h1 className="vn-title-page" style={{ margin: 0 }}>Token health</h1>
          <p className="vn-page-desc">Credential state across the fleet. An expired credential drives the account's health axis to expired — a fix action, not a mystery.</p></div>
        <div className="vn-page-actions"><Button icon="heart-pulse">Check all</Button></div>
      </div>
      <DataTable label="Credential health" rowKey="id" rows={rows}
        columns={[
          { key: "account", label: "Provider · account", mono: true },
          { key: "kind", label: "Credential", render: (r) => <CredentialKindBadge kind={r.kind} /> },
          { key: "exp", label: "Expiry", mono: true, render: (r) => r.status === "expired" ? <Badge tone="warning" icon="key-round">{r.exp}</Badge> : r.exp },
          { key: "status", label: "Status", render: (r) => <AccountStatus status={r.status} /> },
          { key: "reauth", label: "Reauth", render: (r) => <ReauthenticationStatus state={r.reauth} /> },
          { key: "act", label: "", render: (r) => r.status === "expired" ? <Button size="sm" icon="fingerprint">Reauthenticate</Button> : null },
        ]} />
      <p className="vn-caption">One active credential per (account, kind); staged replacements coexist during reauth; retired rows are kept for audit. Secrets never appear here — reveal is a separate, re-verified action.</p>
    </React.Fragment>
  );
};

// ---------- 11. Diagnostics ----------
export function Diagnostics() {
  const [row, setRow] = React.useState(null);
  const [q, setQ] = React.useState("");
  const rows = [
    { id: "req_01J9ZK4T7Q", time: "14:03:11Z", tier: "max", outcome: "ok", route: "claude-code : sonnet-4-5", attempts: 2, latency: "1,204 ms" },
    { id: "req_01J9ZJ8Q2M", time: "13:59:02Z", tier: "lite", outcome: "ok", route: "opencode-zen : glm-5", attempts: 1, latency: "612 ms" },
    { id: "req_01J9ZH1V9C", time: "13:44:19Z", tier: "lite", outcome: "failed_closed", route: "—", attempts: 3, latency: "38 ms" },
  ];
  const sel = rows.find((r) => r.id === (row && row.id));
  return (
    <React.Fragment>
      <div className="vn-page-header">
        <div><h1 className="vn-title-page" style={{ margin: 0 }}>Diagnostics</h1>
          <p className="vn-page-desc">Why did this route? Decision records store candidates, typed exclusion codes, and scores — never prompts, responses, or raw provider errors.</p></div>
      </div>
      <FilterBar searchValue={q} onSearchChange={setQ} searchPlaceholder="Find request id">
        <span className="vn-caption">last 24h · 6,642 decisions</span>
      </FilterBar>
      <DataTable label="Route decisions" rowKey="id" rows={rows} onRowClick={setRow} selectedKey={sel && sel.id}
        columns={[
          { key: "time", label: "Time", mono: true },
          { key: "id", label: "Request", mono: true },
          { key: "tier", label: "Tier", render: (r) => <TierBadge tier={r.tier} /> },
          { key: "route", label: "Chosen route", mono: true },
          { key: "attempts", label: "Attempts", numeric: true },
          { key: "latency", label: "Latency", numeric: true },
          { key: "outcome", label: "Outcome", render: (r) => r.outcome === "ok" ? <Badge tone="healthy" icon="circle-check">routed</Badge> : <Badge tone="warning" icon="ban">failed closed</Badge> },
        ]} />
      <Drawer open={!!sel} onClose={() => setRow(null)} title={sel ? "Route decision" : ""} wide>
        {sel && (
          <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-4)" }}>
            <div style={{ display: "flex", gap: "var(--space-2)", alignItems: "center" }}><TraceId id={sel.id} /><TierBadge tier={sel.tier} /></div>
            {sel.outcome === "failed_closed" ? (
              <TypedErrorDisplay tone="warning" code="venom_free_capacity_exhausted" retryable retryAfter="6m 40s" requestId={sel.id}
                message="venom/lite free capacity was exhausted. Lite fails closed — it never uses paid or unknown-cost accounts." />
            ) : null}
            <RouteDecisionTrace candidates={[
              { route: "claude-code : sonnet-4-5 : paid", funding: "paid", quality: 0.91, score: 0.84, outcome: sel.outcome === "ok" ? "chosen" : "excluded", reasons: sel.outcome === "ok" ? [] : ["funding_unknown"], clamp: sel.tier === "pro" ? "ultra→extended" : undefined },
              { route: "opencode-zen : glm-5 : free", funding: "free", quality: 0.88, score: 0.8, outcome: "in_band" },
              { route: "codex : gpt-5.2 : paid", funding: "paid", quality: 0.79, score: null, outcome: "excluded", reasons: ["quota_exhausted", "cooling_down"] },
            ]} />
            <RoutingAttemptTimeline attempts={[
              { route: "codex : gpt-5.2 · dev@venom.local", outcome: "failed", reservation: "released", code: "rate_limit", detail: "429 scope=offering → cooldown 41s; reservation released (never consumed)", latency: "310 ms" },
              { route: "claude-code : sonnet-4-5 · ops@venom.local", outcome: "succeeded", reservation: "settled", detail: "reserved across provider:five_hour + local:concurrency → executed → settled (actual)", latency: "1,204 ms" },
            ]} />
            <RawPayloadDisclosure label="Decision record (sanitized)" redactedFields={["account external ids"]}
              payload={'{\n  "request_id": "' + sel.id + '",\n  "tier": "' + sel.tier + '",\n  "excluded": [{"route": "agnes-ai:kimi-k2.5", "reasons": ["funding_unknown"]}]\n}'} />
          </div>
        )}
      </Drawer>
    </React.Fragment>
  );
};

// ---------- 17. Tier status ----------
export function TierStatus() {
  const tiers = [
    { t: "lite", state: <Badge tone="healthy" icon="circle-check">eligible</Badge>, notes: [
      "9 certified free routes · verified context ≥ 256K", "Free-safety: all offerings verified zero-cost (provider price or models.dev, exact match)"],
      caps: "chat · streaming · tools · structured output · vision · reasoning (no thinking budget)", used: 36, reasons: [] },
    { t: "pro", state: <Badge tone="healthy" icon="circle-check">eligible</Badge>, notes: [
      "23 routes in pool · paid share 22% vs 25% target (within ±5pp)", "Extended thinking enabled · 512K ceiling"],
      caps: "full V1 surface · extended thinking", used: 58, reasons: [] },
    { t: "max", state: <Badge tone="degraded" icon="triangle-alert">degraded</Badge>, notes: [
      "Quality band top 0.91 · 4 in band", "2 of 5 eligible accounts saturated on a required window — DRR skips them"],
      caps: "full V1 surface · ultra thinking · 1M ceiling", used: 91, reasons: ["quota_insufficient", "cooling_down"] },
  ];
  return (
    <React.Fragment>
      <div className="vn-page-header">
        <div><h1 className="vn-title-page" style={{ margin: 0 }}>Tier status</h1>
          <p className="vn-page-desc">Live eligibility per product. A tier that cannot serve a capability reports honest coverage and fails closed — it never crosses funding pools.</p></div>
      </div>
      {tiers.map((r) => (
        <Panel key={r.t} title={<span style={{ display: "inline-flex", gap: "var(--space-2)", alignItems: "center" }}><TierBadge tier={r.t} />{r.state}</span>}>
          <div style={{ padding: "var(--space-3) var(--space-4)", display: "grid", gridTemplateColumns: "1fr 260px", gap: "var(--space-4)", alignItems: "start" }}>
            <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-1)" }}>
              {r.notes.map((n, i) => <span key={i} className="vn-body-compact">{n}</span>)}
              <span className="vn-caption">{r.caps}</span>
              {r.reasons.length ? (
                <span style={{ display: "flex", gap: 6, marginTop: 4, flexWrap: "wrap" }}>
                  {r.reasons.map((c) => <CandidateRejectionReason key={c} code={c} />)}
                </span>
              ) : null}
            </div>
            <div><span className="vn-caption">pooled quota pressure</span><Meter value={r.used} max={100} label={r.t + " usage"} /></div>
          </div>
        </Panel>
      ))}
    </React.Fragment>
  );
};
