// Venom Design System — token build pipeline.
// The tokens/*.json files are the SOLE authored source. This script compiles them to:
//   tokens/primitives.css        (theme-agnostic scales)
//   themes/venom-dark.css        (default; bound to :root and [data-theme="venom-dark"])
//   themes/venom-light.css
//   tokens/components.css        (component tokens -> semantic var() references)
//   tokens/density.css           (comfortable/compact via [data-density])
//   tokens/accents.css           (optional accent palettes via [data-accent])
//   tokens/tokens.ts             (typed token object)
//   tokens/tailwind-theme.ts     (Tailwind theme extension — utilities resolve to var(--…))
//   validation/theme-token-manifest.json (resolved values per theme, for contrast/completeness gates)
// Generated files carry a GENERATED header — never hand-edit them.
// It also enforces, at build time: identical semantic token sets across all themes;
// no unresolved alias; component tokens may reference ONLY semantic tokens;
// semantic tokens may reference primitives or sibling semantics; primitives reference nothing.
//
// Usage (browser sandbox): eval this file, then `await buildVenomTokens(io)` with
//   io = { readFile(path)->string, saveFile(path, string), log(...args) }.
// Usage (node): node -e "globalThis.module={};" ... or adapt with fs-based io.

async function buildVenomTokens(io) {
  const { readFile, saveFile, log } = io;
  const HEADER = (src) => `/* GENERATED by validation/build-tokens.cjs from ${src} — DO NOT EDIT BY HAND. */\n`;
  const ALIAS = /^\{([^}]+)\}$/;

  const parse = async (p) => JSON.parse(await readFile(p));
  const primitivesDoc = await parse('tokens/tokens.primitive.json');
  const themeFiles = {
    'venom-dark': 'tokens/tokens.semantic.venom-dark.json',
    'venom-light': 'tokens/tokens.semantic.venom-light.json',
  };
  const componentDoc = await parse('tokens/tokens.component.json');
  const densityDoc = await parse('tokens/tokens.density.json');
  const accentsDoc = await parse('tokens/tokens.accents.json');

  // ---- flatten: {a:{b:{$value:x}}} -> Map("a.b" -> x), skipping $-keys
  function flatten(node, path = [], out = new Map()) {
    if (node && typeof node === 'object') {
      if ('$value' in node) { out.set(path.join('.'), String(node.$value)); return out; }
      for (const [k, v] of Object.entries(node)) {
        if (k.startsWith('$')) continue;
        flatten(v, path.concat(k), out);
      }
    }
    return out;
  }
  const cssName = (dotted) => '--' + dotted.replace(/\./g, '-');

  const prim = flatten(primitivesDoc);
  const themes = {};
  for (const [name, file] of Object.entries(themeFiles)) themes[name] = flatten(await parse(file));

  // ---- Gate: theme completeness (identical sets, no missing, no extra)
  const setsEqual = (a, b) => a.length === b.length && a.every((k, i) => k === b[i]);
  const keysByTheme = Object.fromEntries(Object.entries(themes).map(([n, m]) => [n, [...m.keys()].sort()]));
  const canon = keysByTheme['venom-dark'];
  const completeness = {};
  for (const [n, keys] of Object.entries(keysByTheme)) {
    const missing = canon.filter((k) => !keys.includes(k));
    const extra = keys.filter((k) => !canon.includes(k));
    completeness[n] = { count: keys.length, missing, extra };
    if (!setsEqual(keys, canon)) throw new Error(`THEME COMPLETENESS FAILED for ${n}: missing=[${missing}] extra=[${extra}]`);
  }

  // ---- Gate: alias legality + resolvability
  function checkAliases(map, scopeName, allowed) {
    for (const [k, v] of map) {
      const m = v.match(ALIAS);
      if (!m) continue;
      const target = m[1];
      if (!allowed.some((s) => s.has(target))) throw new Error(`UNRESOLVED TOKEN REFERENCE in ${scopeName}: ${k} -> {${target}}`);
    }
  }
  checkAliases(prim, 'primitives', []); // primitives must be literal
  for (const [n, m] of Object.entries(themes)) checkAliases(m, `theme ${n}`, [prim, m]);
  const comp = flatten(componentDoc);
  // component tokens: reference semantic ONLY (validate against the canonical semantic set)
  const semanticSet = new Map(canon.map((k) => [k, true]));
  for (const [k, v] of comp) {
    const m = v.match(ALIAS);
    if (!m) throw new Error(`COMPONENT TOKEN MUST ALIAS A SEMANTIC TOKEN: ${k} = ${v}`);
    if (!semanticSet.has(m[1])) throw new Error(`COMPONENT TOKEN REFERENCES NON-SEMANTIC TARGET: ${k} -> {${m[1]}}`);
  }

  // ---- resolve raw value (follow alias chain) within (prim + theme)
  function resolveRaw(dotted, themeMap, depth = 0) {
    if (depth > 8) throw new Error('Alias cycle at ' + dotted);
    const v = themeMap.get(dotted) ?? prim.get(dotted);
    if (v == null) throw new Error('Unknown token ' + dotted);
    const m = v.match(ALIAS);
    return m ? resolveRaw(m[1], themeMap, depth + 1) : v;
  }
  const toCss = (v) => { const m = v.match(ALIAS); return m ? `var(${cssName(m[1])})` : v; };

  // ---- emit primitives.css
  let out = HEADER('tokens/tokens.primitive.json') + ':root {\n';
  for (const [k, v] of prim) out += `  ${cssName(k)}: ${v};\n`;
  out += '}\n';
  await saveFile('tokens/primitives.css', out);

  // ---- emit theme css
  for (const [name, map] of Object.entries(themes)) {
    const sel = name === 'venom-dark' ? `:root,\n[data-theme="venom-dark"]` : `[data-theme="${name}"]`;
    let css = HEADER(themeFiles[name]) + sel + ' {\n  color-scheme: ' + (name === 'venom-light' ? 'light' : 'dark') + ';\n';
    for (const [k, v] of map) css += `  ${cssName(k)}: ${toCss(v)};\n`;
    css += '}\n';
    await saveFile(`themes/${name}.css`, css);
  }

  // ---- emit components.css — one block PER THEME (not a single shared :root block).
  // Component tokens alias semantic tokens via var(); if declared once at :root, that
  // var() reference resolves using :root's OWN cascade (whatever theme the <html> element
  // carries) and the already-resolved color is what inherits down — a nested
  // [data-theme="x"] element never gets to re-resolve it. Redeclaring the identical
  // var(--semantic-*) reference under each theme's own selector makes it re-resolve
  // correctly wherever a theme is applied, including nested (not just root-level) scoping.
  let ccss = HEADER('tokens/tokens.component.json');
  for (const name of Object.keys(themes)) {
    const sel = name === 'venom-dark' ? `:root,\n[data-theme="venom-dark"]` : `[data-theme="${name}"]`;
    ccss += sel + ' {\n';
    for (const [k, v] of comp) ccss += `  ${cssName(k)}: ${toCss(v)};\n`;
    ccss += '}\n';
  }
  await saveFile('tokens/components.css', ccss);

  // ---- emit density.css
  function flattenDensity(node, path = [], out = []) {
    if (node && typeof node === 'object') {
      if ('comfortable' in node && 'compact' in node) { out.push([path.join('.'), node]); return out; }
      for (const [k, v] of Object.entries(node)) { if (!k.startsWith('$')) flattenDensity(v, path.concat(k), out); }
    }
    return out;
  }
  const dens = flattenDensity(densityDoc);
  // Spacing-type density tokens (pads, gaps) are multiplied by the runtime spacing scale
  // --vn-spacing-scale (default 1; set via applySpacing from src/customizer.ts, clamped
  // 0.75-1.25). Control/row HEIGHTS are deliberately excluded: they are density-owned
  // control metrics, not layout spacing. At the default scale the computed values are
  // byte-for-byte today's px values.
  const densityValue = (key, raw) => (/height/.test(key) ? raw : `calc(${raw} * var(--vn-spacing-scale, 1))`);
  let dcss = HEADER('tokens/tokens.density.json');
  dcss += ':root,\n[data-density="comfortable"] {\n';
  for (const [k, v] of dens) dcss += `  ${cssName('density.' + k)}: ${densityValue(k, v.comfortable)};\n`;
  dcss += '}\n[data-density="compact"] {\n';
  for (const [k, v] of dens) dcss += `  ${cssName('density.' + k)}: ${densityValue(k, v.compact)};\n`;
  dcss += '}\n';
  await saveFile('tokens/density.css', dcss);

  // ---- emit accents.css — optional accent palettes as [data-accent="…"] override blocks.
  // Each accent may override ONLY the accent-derived semantic custom properties below —
  // the build fails loudly on any other key, so an accent can never restyle surfaces,
  // status colors, or text roles. `base` carries the venom-dark values (dark is the
  // :root default theme); a `themes.<name>` block re-overrides for that theme at higher
  // attribute specificity ([data-theme="…"][data-accent="…"]).
  const ACCENT_ALLOWED = [
    'accent.default', 'accent.hover', 'accent.active', 'accent.subtle-bg', 'accent.text',
    'text.on-accent', 'text.link', 'text.link-hover',
    'border.focus', 'focus.ring',
    'selection.bg', 'selection.fg',
  ];
  const accentDefs = accentsDoc.accents || {};
  let accentBlockCount = 0;
  const emitAccentBlock = (selector, entries, scopeName) => {
    const keys = Object.keys(entries);
    for (const k of keys) {
      if (!ACCENT_ALLOWED.includes(k)) throw new Error(`ACCENT OVERRIDES A NON-ACCENT-DERIVED TOKEN in ${scopeName}: ${k}`);
    }
    const missing = ACCENT_ALLOWED.filter((k) => !keys.includes(k));
    if (missing.length) throw new Error(`ACCENT BLOCK INCOMPLETE in ${scopeName}: missing [${missing}]`);
    let block = selector + ' {\n';
    for (const k of ACCENT_ALLOWED) block += `  ${cssName(k)}: ${toCss(String(entries[k]))};\n`;
    block += '}\n';
    accentBlockCount++;
    return block;
  };
  let acss = HEADER('tokens/tokens.accents.json');
  for (const [name, def] of Object.entries(accentDefs)) {
    if (!/^[a-z][a-z0-9-]*$/.test(name)) throw new Error('ACCENT NAME MUST BE lowercase kebab: ' + name);
    if (name === 'mono') throw new Error('ACCENT "mono" is the base theme identity — it must not ship an override block');
    acss += emitAccentBlock(`[data-accent="${name}"]`, def.base || {}, `accent ${name} (base)`);
    for (const [themeName, overrides] of Object.entries(def.themes || {})) {
      if (!themes[themeName]) throw new Error(`ACCENT ${name} TARGETS UNKNOWN THEME: ${themeName}`);
      acss += emitAccentBlock(`[data-theme="${themeName}"][data-accent="${name}"]`, overrides, `accent ${name} (${themeName})`);
    }
  }
  await saveFile('tokens/accents.css', acss);

  // ---- emit tokens.ts
  const tsObj = {
    primitive: Object.fromEntries([...prim.keys()].map((k) => [k, `var(${cssName(k)})`])),
    semantic: Object.fromEntries(canon.map((k) => [k, `var(${cssName(k)})`])),
    component: Object.fromEntries([...comp.keys()].map((k) => [k, `var(${cssName(k)})`])),
    density: Object.fromEntries(dens.map(([k]) => ['density.' + k, `var(${cssName('density.' + k)})`])),
  };
  const ts = `// GENERATED by validation/build-tokens.cjs — DO NOT EDIT BY HAND.
// Typed access to every Venom design token as a CSS custom-property reference.
export const tokens = ${JSON.stringify(tsObj, null, 2)} as const;
export type SemanticToken = keyof typeof tokens.semantic;
export type ComponentToken = keyof typeof tokens.component;
export type PrimitiveToken = keyof typeof tokens.primitive;
`;
  await saveFile('tokens/tokens.ts', ts);

  // ---- emit tokens/tailwind-theme.ts — the third mandated compiled output (docs/07 §2.3/§10).
  // Every value is a var(--…) reference to the generated CSS custom properties, so Tailwind
  // utilities re-resolve under data-theme / data-density at runtime and can never drift from
  // the authored tokens. The one exception is `screens`: media queries cannot read CSS custom
  // properties, so breakpoints carry the literal primitive values. Component-layer tokens are
  // deliberately excluded — screens compose inventory components and never restyle their parts.
  const setDeep = (obj, dotted, value) => {
    const parts = dotted.split('.');
    let cur = obj;
    for (const p of parts.slice(0, -1)) cur = cur[p] = cur[p] || {};
    cur[parts[parts.length - 1]] = value;
  };
  const varRef = (dotted) => `var(${cssName(dotted)})`;
  const isColorValue = (v) => /^#([0-9a-fA-F]{3,8})$/.test(v.trim()) || /^rgba?\(/.test(v.trim());

  const twColors = {};
  const twElevation = {};
  const twOutlineWidth = {};
  const twOutlineOffset = {};
  for (const k of canon) {
    if (k.startsWith('elevation.')) { twElevation[k.slice('elevation.'.length)] = varRef(k); continue; }
    if (k === 'focus.ring-width') { twOutlineWidth.focus = varRef(k); continue; }
    if (k === 'focus.ring-offset') { twOutlineOffset.focus = varRef(k); continue; }
    // Classified against the resolved venom-dark value; the EMITTED value is always the
    // theme-agnostic var() reference (identical semantic token set across themes is already
    // enforced above, so one theme suffices for classification).
    if (isColorValue(resolveRaw(k, themes['venom-dark']))) { setDeep(twColors, k, varRef(k)); continue; }
    // Fail loud: a future non-color semantic token must be mapped here explicitly,
    // never silently dropped from the Tailwind output.
    throw new Error('TAILWIND EMIT: unmapped non-color semantic token ' + k + ' — extend the Tailwind emitter in validation/build-tokens.cjs');
  }
  const pickPrim = (prefix) => {
    const out = {};
    for (const [k] of prim) if (k.startsWith(prefix + '.')) out[k.slice(prefix.length + 1)] = varRef(k);
    return out;
  };
  const twScreens = {};
  for (const [k, v] of prim) if (k.startsWith('breakpoint.')) twScreens[k.slice('breakpoint.'.length)] = v;
  const twControlHeights = {};
  for (const [k] of dens) if (k.startsWith('control.height.')) twControlHeights['control-' + k.slice('control.height.'.length)] = varRef('density.' + k);

  const twTheme = {
    colors: twColors,
    spacing: pickPrim('space'),
    borderRadius: pickPrim('radius'),
    borderWidth: pickPrim('border'),
    fontFamily: pickPrim('font.family'),
    fontSize: pickPrim('font.size'),
    fontWeight: pickPrim('font.weight'),
    lineHeight: pickPrim('font.line-height'),
    letterSpacing: pickPrim('font.tracking'),
    boxShadow: { ...pickPrim('shadow'), ...twElevation },
    zIndex: pickPrim('z'),
    transitionDuration: pickPrim('duration'),
    transitionTimingFunction: pickPrim('easing'),
    outlineWidth: twOutlineWidth,
    outlineOffset: twOutlineOffset,
    height: twControlHeights,
    screens: twScreens,
  };
  const tw = `// GENERATED by validation/build-tokens.cjs from tokens/tokens.primitive.json,
// tokens/tokens.semantic.*.json and tokens/tokens.density.json — DO NOT EDIT BY HAND.
//
// The Tailwind theme extension — the third compiled token output alongside the CSS
// custom properties and the typed tokens object. Every value is a var(--…) reference
// to the generated CSS custom properties, so utilities re-resolve under data-theme /
// data-density at runtime and can never drift from the authored tokens.
// Exception: \`screens\` — media queries cannot read CSS custom properties, so
// breakpoints carry the literal primitive values.
// Component-layer tokens are deliberately excluded: screens compose inventory
// components and never restyle their parts.
export const venomTailwindTheme = ${JSON.stringify(twTheme, null, 2)} as const;

/** Drop-in Tailwind preset: \`presets: [venomTailwindPreset]\` in tailwind.config. */
export const venomTailwindPreset = { theme: { extend: venomTailwindTheme } } as const;

export type VenomTailwindTheme = typeof venomTailwindTheme;
`;
  await saveFile('tokens/tailwind-theme.ts', tw);

  // ---- emit resolved manifest for downstream gates (contrast, completeness reporting)
  const manifest = { generatedBy: 'validation/build-tokens.cjs', semanticTokenCount: canon.length, completeness, themes: {} };
  for (const [name, map] of Object.entries(themes)) {
    manifest.themes[name] = Object.fromEntries(canon.map((k) => [k, resolveRaw(k, map)]));
  }
  await saveFile('validation/theme-token-manifest.json', JSON.stringify(manifest, null, 2));

  log(`OK: ${prim.size} primitives, ${canon.length} semantic tokens x ${Object.keys(themes).length} themes, ${comp.size} component tokens, ${dens.length} density tokens, ${Object.keys(accentDefs).length} accents (${accentBlockCount} override blocks), ${Object.keys(twTheme).length} tailwind theme groups.`);
  return manifest.completeness;
}

if (typeof module !== 'undefined') module.exports = { buildVenomTokens };
