/**
 * Public entry point: design tokens.
 * Typed access to every generated CSS custom property. `tokens/tokens.ts` is GENERATED by
 * `validation/build-tokens.js` from the authored JSON in `tokens/*.json` — never hand-edited.
 */
export * from "../tokens/tokens";
