package providers

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"time"
)

// ClinePassID is the catalog slug this adapter registers under.
const ClinePassID ProviderID = "clinepass"

// clinepass endpoints (03 §3; verified against the legacy implementation
// 2026-08-03). The base MUST equal the BuiltinCatalog entry — asserted by a
// test. The paths below are appended to it.
const (
	ClinePassBaseURL = "https://api.cline.bot"

	clinePassAuthorizePath = "/api/v1/auth/authorize"
	clinePassTokenPath     = "/api/v1/auth/token"
	clinePassRefreshPath   = "/api/v1/auth/refresh"
	clinePassIdentityPath  = "/api/v1/users/me"
	clinePassModelsPath    = "/api/v1/ai/cline/recommended-models"
	clinePassBalancePath   = "/api/v1/users/me/balance"

	clinePassConfidence = 1.0
)

// ClinePassPostProbe performs a JSON POST (token / refresh — clinepass uses
// JSON bodies, not form). It returns the raw status + body so the adapter can
// classify and parse. body must never be logged (it carries the code / refresh
// token).
type ClinePassPostProbe func(ctx context.Context, url string, body []byte) (statusCode int, respBody []byte, err error)

// ClinePassGetProbe performs an authenticated GET (identity / discovery /
// quota). The concrete implementation applies the wire decoration clinepass
// needs (the workos: Bearer prefix and the cline headers); accessToken is never
// logged. It returns the raw status so the adapter can classify.
type ClinePassGetProbe func(ctx context.Context, url, accessToken string) (statusCode int, body []byte, err error)

// clinePassTokenResponse tolerates both camelCase (the shape the verified
// refresh REQUEST body uses) and snake_case for the token endpoint response —
// the exact response casing is confirmed on live re-verification.
type clinePassTokenResponse struct {
	AccessToken   string `json:"access_token"`
	AccessTokenC  string `json:"accessToken"`
	RefreshToken  string `json:"refresh_token"`
	RefreshTokenC string `json:"refreshToken"`
	ExpiresIn     int64  `json:"expires_in"`
	ExpiresInC    int64  `json:"expiresIn"`
}

func (r clinePassTokenResponse) access() string {
	if r.AccessToken != "" {
		return r.AccessToken
	}
	return r.AccessTokenC
}
func (r clinePassTokenResponse) refresh() string {
	if r.RefreshToken != "" {
		return r.RefreshToken
	}
	return r.RefreshTokenC
}
func (r clinePassTokenResponse) expiresIn() int64 {
	if r.ExpiresIn != 0 {
		return r.ExpiresIn
	}
	return r.ExpiresInC
}

// clinePassIdentity is the subset of GET /api/v1/users/me this adapter reads:
// clineUserId is the stable external id (03 §3).
type clinePassIdentity struct {
	ClineUserID string `json:"clineUserId"`
	Email       string `json:"email"`
}

type clinePassStoredToken struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresAt    int64  `json:"expires_at"`
}

// ClinePassAdapter implements OAuthAdapter + Identity/Discovery/Quota/Health for
// clinepass (03 §3): an OAuth extension flow where a PKCE verifier IS generated
// by the framework but is NOT sent on the wire. Funding is PAID and LOCKED (the
// catalog's Locked flag makes an owner override fail funding_locked). Its route
// speaks the openai_chat wire schema; the workos: Bearer prefix and cline
// headers are the TRANSPORT's job (P7-EXEC-001), so the stored token stays raw.
type ClinePassAdapter struct {
	postProbe ClinePassPostProbe
	getProbe  ClinePassGetProbe
}

// NewClinePassAdapter builds the adapter over the two injected seams.
func NewClinePassAdapter(postProbe ClinePassPostProbe, getProbe ClinePassGetProbe) *ClinePassAdapter {
	return &ClinePassAdapter{postProbe: postProbe, getProbe: getProbe}
}

// BeginOAuth builds the extension-flow authorize URL. The PKCE verifier is
// generated by the framework but is DELIBERATELY NOT sent on the wire: this is
// clinepass's documented extension flow (03 §3), NOT an oversight — a future
// reader must not "fix" it by adding code_challenge, so a test pins its absence.
// pkceChallenge is intentionally ignored for that reason.
func (a *ClinePassAdapter) BeginOAuth(_ context.Context, redirectURI, state, _ string) (string, error) {
	q := url.Values{}
	q.Set("response_type", "code")
	q.Set("client_type", "extension")
	q.Set("provider", "clinepass")
	q.Set("redirect_uri", redirectURI)
	q.Set("callback_url", redirectURI)
	q.Set("state", state)
	return ClinePassBaseURL + clinePassAuthorizePath + "?" + q.Encode(), nil
}

// CompleteOAuth exchanges the code (JSON body; NO code_verifier — the verifier
// is not sent), then fetches identity. A 2xx users/me without clineUserId is a
// typed failure, never a fabricated identity. Funding is reported paid.
func (a *ClinePassAdapter) CompleteOAuth(ctx context.Context, code, _ /*pkceVerifier*/, redirectURI string) (IdentityResult, StoredCredentials, error) {
	reqBody, _ := json.Marshal(map[string]string{
		"grant_type":   "authorization_code",
		"client_type":  "extension",
		"provider":     "clinepass",
		"code":         code,
		"redirect_uri": redirectURI,
	})
	tok, err := a.exchange(ctx, ClinePassBaseURL+clinePassTokenPath, reqBody)
	if err != nil {
		return IdentityResult{}, StoredCredentials{}, err
	}

	identity, err := a.fetchIdentity(ctx, tok.access())
	if err != nil {
		return IdentityResult{}, StoredCredentials{}, err
	}
	if identity.ClineUserID == "" {
		return IdentityResult{}, StoredCredentials{}, ErrMissingStableIdentity
	}

	stored, err := marshalClinePassToken(tok.access(), tok.refresh(), tok.expiresIn())
	if err != nil {
		return IdentityResult{}, StoredCredentials{}, err
	}
	// Funding here is REPORTED, not authoritative: clinepass's catalog entry is
	// FundingModeFixed{Fixed: paid, Locked: true}, and
	// application.firstFundingEvidence consults IdentityResult.Funding ONLY for
	// FundingModeProviderEvidence providers. So the stamped evidence — and the
	// 409 funding_locked an owner override earns (domain.ErrFundingLocked) — come
	// from the catalog, not from this field. It is set to the same value on
	// purpose (a disagreement would be a lie in the audit trail), but changing it
	// alone changes NO behaviour: the lock lives in catalog.go + the frozen
	// funding domain, which is where the test pins it.
	return IdentityResult{
		ExternalID: identity.ClineUserID,
		Email:      identity.Email,
		Plan:       "ClinePass",
		Funding:    string(FundingPaid),
		Confidence: clinePassConfidence,
		Evidence:   map[string]any{"funding_source": "clinepass_locked_paid"},
	}, stored, nil
}

// RefreshCredentials posts {refreshToken, grantType:"refresh_token"} (camelCase,
// 03 §3). Same retention rules as claude-code: keep the old refresh token when
// none is returned; a failed refresh returns a typed error and leaves the
// stored credential untouched.
func (a *ClinePassAdapter) RefreshCredentials(ctx context.Context, creds StoredCredentials) (StoredCredentials, error) {
	var stored clinePassStoredToken
	if err := json.Unmarshal([]byte(creds.Value), &stored); err != nil {
		return StoredCredentials{}, fmt.Errorf("providers: clinepass: refresh: parse stored credentials: %w", err)
	}
	if stored.RefreshToken == "" {
		return StoredCredentials{}, errors.New("providers: clinepass: refresh: no refresh token available")
	}
	reqBody, _ := json.Marshal(map[string]string{"refreshToken": stored.RefreshToken, "grantType": "refresh_token"})
	tok, err := a.exchange(ctx, ClinePassBaseURL+clinePassRefreshPath, reqBody)
	if err != nil {
		return StoredCredentials{}, err
	}
	newRefresh := tok.refresh()
	if newRefresh == "" {
		newRefresh = stored.RefreshToken
	}
	return marshalClinePassToken(tok.access(), newRefresh, tok.expiresIn())
}

func (a *ClinePassAdapter) exchange(ctx context.Context, url string, body []byte) (clinePassTokenResponse, error) {
	status, respBody, err := a.postProbe(ctx, url, body)
	if err != nil {
		return clinePassTokenResponse{}, fmt.Errorf("providers: clinepass: token endpoint: %w", err)
	}
	if status == 401 || status == 403 {
		return clinePassTokenResponse{}, ErrInvalidCredential
	}
	if status < 200 || status >= 300 {
		return clinePassTokenResponse{}, ErrProviderUnavailable
	}
	var tok clinePassTokenResponse
	if err := json.Unmarshal(respBody, &tok); err != nil {
		return clinePassTokenResponse{}, fmt.Errorf("providers: clinepass: parse token response: %w", err)
	}
	if tok.access() == "" {
		return clinePassTokenResponse{}, ErrInvalidCredential
	}
	return tok, nil
}

func marshalClinePassToken(access, refresh string, expiresIn int64) (StoredCredentials, error) {
	value, err := json.Marshal(clinePassStoredToken{
		AccessToken:  access,
		RefreshToken: refresh,
		ExpiresAt:    time.Now().Add(time.Duration(expiresIn) * time.Second).Unix(),
	})
	if err != nil {
		return StoredCredentials{}, fmt.Errorf("providers: clinepass: marshal stored credentials: %w", err)
	}
	return StoredCredentials{Value: string(value)}, nil
}

func (a *ClinePassAdapter) fetchIdentity(ctx context.Context, accessToken string) (clinePassIdentity, error) {
	status, body, err := a.getProbe(ctx, ClinePassBaseURL+clinePassIdentityPath, accessToken)
	if err != nil {
		return clinePassIdentity{}, fmt.Errorf("providers: clinepass: fetch identity: %w", err)
	}
	if status == 401 || status == 403 {
		return clinePassIdentity{}, ErrInvalidCredential
	}
	if status < 200 || status >= 300 {
		return clinePassIdentity{}, ErrProviderUnavailable
	}
	var id clinePassIdentity
	if err := json.Unmarshal(body, &id); err != nil {
		return clinePassIdentity{}, fmt.Errorf("providers: clinepass: parse identity: %w", err)
	}
	return id, nil
}

// FetchIdentity implements IdentityAdapter over the stored token.
func (a *ClinePassAdapter) FetchIdentity(ctx context.Context, creds StoredCredentials) (IdentityResult, error) {
	token, err := clinePassAccessToken(creds)
	if err != nil {
		return IdentityResult{}, err
	}
	id, err := a.fetchIdentity(ctx, token)
	if err != nil {
		return IdentityResult{}, err
	}
	if id.ClineUserID == "" {
		return IdentityResult{}, ErrMissingStableIdentity
	}
	return IdentityResult{ExternalID: id.ClineUserID, Email: id.Email, Plan: "ClinePass", Funding: string(FundingPaid), Confidence: clinePassConfidence}, nil
}

// clinePassModelList tolerates a `models` array of {id|modelId, name}; the exact
// recommended-models grouping is confirmed on live re-verification.
type clinePassModelList struct {
	Models []struct {
		ID      string `json:"id"`
		ModelID string `json:"modelId"`
		Name    string `json:"name"`
	} `json:"models"`
}

// DiscoverModels reads GET /recommended-models and reports explicit facts only
// (id + display name; chat capability, since the recommended list is the set of
// chat models clinepass offers). No limit fields are read, so limits stay nil.
func (a *ClinePassAdapter) DiscoverModels(ctx context.Context, creds StoredCredentials) ([]DiscoveredModel, error) {
	token, err := clinePassAccessToken(creds)
	if err != nil {
		return nil, err
	}
	status, body, err := a.getProbe(ctx, ClinePassBaseURL+clinePassModelsPath, token)
	if err != nil {
		return nil, fmt.Errorf("providers: clinepass: discover models: %w", err)
	}
	if status < 200 || status >= 300 {
		return nil, fmt.Errorf("providers: clinepass: discover models: status %d", status)
	}
	var list clinePassModelList
	if err := json.Unmarshal(body, &list); err != nil {
		return nil, fmt.Errorf("providers: clinepass: parse models: %w", err)
	}
	out := make([]DiscoveredModel, 0, len(list.Models))
	for _, m := range list.Models {
		id := m.ID
		if id == "" {
			id = m.ModelID
		}
		if id == "" {
			continue
		}
		display := m.Name
		if display == "" {
			display = id
		}
		out = append(out, DiscoveredModel{ProviderModelID: id, DisplayName: display, Capabilities: []string{"chat"}})
	}
	return out, nil
}

// clinePassBalance is the subset of the balance payload this adapter grounds a
// quota window on. Only an explicit credits/balance number produces a window;
// anything else yields NO window (never a fabricated one). The fuller
// usages/usage-limits mapping is deferred to live re-verification (see report).
type clinePassBalance struct {
	Credits *float64 `json:"credits"`
	Balance *float64 `json:"balance"`
}

// FetchQuota maps the balance payload onto a single balance QuotaWindow when a
// credits/balance number is present; otherwise it returns NO windows (an empty
// slice is "no evidence", never "unlimited").
func (a *ClinePassAdapter) FetchQuota(ctx context.Context, creds StoredCredentials) (QuotaResult, error) {
	token, err := clinePassAccessToken(creds)
	if err != nil {
		return QuotaResult{}, err
	}
	status, body, err := a.getProbe(ctx, ClinePassBaseURL+clinePassBalancePath, token)
	if err != nil {
		return QuotaResult{}, fmt.Errorf("providers: clinepass: fetch quota: %w", err)
	}
	if status < 200 || status >= 300 {
		return QuotaResult{}, fmt.Errorf("providers: clinepass: fetch quota: status %d", status)
	}
	var bal clinePassBalance
	if err := json.Unmarshal(body, &bal); err != nil {
		return QuotaResult{}, fmt.Errorf("providers: clinepass: parse balance: %w", err)
	}
	remaining := bal.Credits
	if remaining == nil {
		remaining = bal.Balance
	}
	if remaining == nil {
		return QuotaResult{}, nil // no grounded balance -> no window
	}
	value := *remaining
	return QuotaResult{Windows: []QuotaWindow{{
		Unit:       "credits",
		WindowType: "balance",
		Remaining:  &value,
		Confidence: clinePassConfidence,
	}}}, nil
}

// CheckAccountHealth reuses the identity GET as the credential-authentic call.
func (a *ClinePassAdapter) CheckAccountHealth(ctx context.Context, creds StoredCredentials) (HealthObservation, error) {
	return a.checkHealth(ctx, creds, "account")
}

// CheckOfferingHealth reuses the account-level probe (no per-model endpoint).
func (a *ClinePassAdapter) CheckOfferingHealth(ctx context.Context, creds StoredCredentials, _ string) (HealthObservation, error) {
	return a.checkHealth(ctx, creds, "offering")
}

func (a *ClinePassAdapter) checkHealth(ctx context.Context, creds StoredCredentials, scope string) (HealthObservation, error) {
	token, err := clinePassAccessToken(creds)
	if err != nil {
		return observationFromValidation(ValidationUnavailable, scope, time.Now().Unix()), nil
	}
	status, _, err := a.getProbe(ctx, ClinePassBaseURL+clinePassIdentityPath, token)
	if err != nil {
		return observationFromValidation(ValidationUnavailable, scope, time.Now().Unix()), nil
	}
	return observationFromValidation(classifyOAuthStatus(status), scope, time.Now().Unix()), nil
}

func clinePassAccessToken(creds StoredCredentials) (string, error) {
	var stored clinePassStoredToken
	if err := json.Unmarshal([]byte(creds.Value), &stored); err != nil {
		return "", fmt.Errorf("providers: clinepass: parse stored credentials: %w", err)
	}
	if stored.AccessToken == "" {
		return "", ErrInvalidCredential
	}
	return stored.AccessToken, nil
}

// RegisterClinePass registers the clinepass OAuth + Identity + Discovery +
// Quota + Health adapters into reg with the native_oauth transport and the
// openai_chat wire schema.
func RegisterClinePass(reg *Registry, postProbe ClinePassPostProbe, getProbe ClinePassGetProbe) error {
	adapter := NewClinePassAdapter(postProbe, getProbe)
	return reg.Register(Definition{
		ID:         ClinePassID,
		AuthMode:   AuthModeOAuth,
		Transport:  TransportKindNativeOAuth,
		WireSchema: WireSchemaOpenAIChat,
		OAuth:      adapter,
		Identity:   adapter,
		Discovery:  adapter,
		Quota:      adapter,
		Health:     adapter,
	})
}
