package providers

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"time"
)

// ClinePassID is the catalog slug this adapter registers under.
const ClinePassID ProviderID = "clinepass"

// clinepass endpoints (03 §3; verified against the legacy implementation
// 2026-08-03). The base MUST equal the BuiltinCatalog entry — asserted by a
// test. The paths below are appended to it.
const (
	ClinePassBaseURL = "https://api.cline.bot"

	clinePassAuthorizePath = "/api/v1/auth/authorize"
	clinePassTokenPath     = "/api/v1/auth/token"
	clinePassRefreshPath   = "/api/v1/auth/refresh"
	clinePassIdentityPath  = "/api/v1/users/me"
	clinePassModelsPath    = "/api/v1/ai/cline/recommended-models"
	// clinePassBalancePath is a TEMPLATE: the real quota call is
	// /api/v1/users/{id}/balance (the numeric user id from /users/me), NOT
	// /users/me/balance — the legacy reference confirmed the dashboard's own
	// balance widget calls it per-user. See FetchQuota.
	clinePassBalancePath     = "/api/v1/users/%s/balance"
	clinePassUsageLimitsPath = "/api/v1/users/me/plan/usage-limits"
	clinePassConfidence      = 1.0
	clinePassMicroPerUSD     = 1_000_000
	clinePassDefaultExpiry   = 3600 // seconds; used only when the token omits expiresAt
)

// ClinePassPostProbe performs a JSON POST (token / refresh — clinepass uses
// JSON bodies, not form). It returns the raw status + body so the adapter can
// classify and parse. body must never be logged (it carries the code / refresh
// token).
type ClinePassPostProbe func(ctx context.Context, url string, body []byte) (statusCode int, respBody []byte, err error)

// ClinePassGetProbe performs an authenticated GET (identity / discovery /
// quota). The concrete implementation applies the wire decoration clinepass
// needs (the workos: Bearer prefix and the cline headers); accessToken is never
// logged. It returns the raw status so the adapter can classify. A blank
// accessToken means NO Authorization header is sent — the recommended-models
// endpoint is public and must not receive a workos:-prefixed header.
type ClinePassGetProbe func(ctx context.Context, url, accessToken string) (statusCode int, body []byte, err error)

// clinePassEnvelope is the wire envelope EVERY authenticated clinepass JSON
// endpoint returns: {success, data, error} (legacy ClineEnvelope, 2026-08-03).
type clinePassEnvelope[T any] struct {
	Success bool   `json:"success"`
	Data    *T     `json:"data"`
	Error   string `json:"error"`
}

// clinePassUserInfo is the user object carried inside the TOKEN RESPONSE's
// data (legacy ClineTokenUserInfo, 2026-08-03) — clineUserId is the stable
// external id (03 §3), subject is the documented fallback.
type clinePassUserInfo struct {
	Subject     string   `json:"subject"`
	Email       string   `json:"email"`
	Name        string   `json:"name"`
	ClineUserID string   `json:"clineUserId"`
	Accounts    []string `json:"accounts"`
}

// clinePassTokenData is the token endpoint's data object: camelCase access/
// refresh tokens, an ISO-string expiresAt, and the userInfo identity. This is
// the REAL shape — the earlier top-level access_token/refresh_token/expires_in
// parsing was drift the legacy reference corrected (2026-08-03).
type clinePassTokenData struct {
	AccessToken  string             `json:"accessToken"`
	RefreshToken string             `json:"refreshToken"`
	ExpiresAt    string             `json:"expiresAt"`
	UserInfo     *clinePassUserInfo `json:"userInfo"`
}

type clinePassIdentity struct {
	ClineUserID string `json:"clineUserId"`
	Email       string `json:"email"`
}

type clinePassStoredToken struct {
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    int64              `json:"expires_at"`
	UserInfo     *clinePassUserInfo `json:"user_info,omitempty"`
}

// ClinePassAdapter implements OAuthAdapter + Identity/Discovery/Quota/Health for
// clinepass (03 §3): an OAuth extension flow where a PKCE verifier IS generated
// by the framework but is NOT sent on the wire. Funding is PAID and LOCKED (the
// catalog's Locked flag makes an owner override fail funding_locked). Its route
// speaks the openai_chat wire schema; the workos: Bearer prefix and cline
// headers are the TRANSPORT's job (P7-EXEC-001), so the stored token stays raw.
type ClinePassAdapter struct {
	postProbe ClinePassPostProbe
	getProbe  ClinePassGetProbe
}

// NewClinePassAdapter builds the adapter over the two injected seams.
func NewClinePassAdapter(postProbe ClinePassPostProbe, getProbe ClinePassGetProbe) *ClinePassAdapter {
	return &ClinePassAdapter{postProbe: postProbe, getProbe: getProbe}
}

// BeginOAuth builds the extension-flow authorize URL with EXACTLY the four
// parameters the reference flow sends (03 §3 / legacy 2026-08-03):
// client_type=extension, callback_url, redirect_uri, state. The PKCE verifier
// is generated by the framework but is DELIBERATELY NOT sent on the wire: this
// is clinepass's documented extension flow, NOT an oversight — a future reader
// must not "fix" it by adding code_challenge, so a test pins its absence.
// pkceChallenge is intentionally ignored for that reason.
func (a *ClinePassAdapter) BeginOAuth(_ context.Context, redirectURI, state, _ string) (string, error) {
	q := url.Values{}
	q.Set("client_type", "extension")
	q.Set("callback_url", redirectURI)
	q.Set("redirect_uri", redirectURI)
	q.Set("state", state)
	return ClinePassBaseURL + clinePassAuthorizePath + "?" + q.Encode(), nil
}

// CompleteOAuth exchanges the code (JSON body; NO code_verifier — the verifier
// is not sent), then resolves identity. The stable external id comes from the
// token response's own userInfo (clineUserId, falling back to subject), with
// GET /users/me as a last-resort fallback — never a fingerprint fabrication.
// Funding is reported paid (see TestClinePass_FundingPaidAndLocked for why the
// lock lives in the catalog, not here).
func (a *ClinePassAdapter) CompleteOAuth(ctx context.Context, code, _ /*pkceVerifier*/, redirectURI string) (IdentityResult, StoredCredentials, error) {
	reqBody, _ := json.Marshal(map[string]string{
		"grant_type":   "authorization_code",
		"client_type":  "extension",
		"provider":     "clinepass",
		"code":         splitOAuthCode(code),
		"redirect_uri": redirectURI,
	})
	tok, err := a.exchange(ctx, ClinePassBaseURL+clinePassTokenPath, reqBody)
	if err != nil {
		return IdentityResult{}, StoredCredentials{}, err
	}

	stableID, email := clinePassStableIdentity(tok.UserInfo)
	if stableID == "" {
		// Fall back to /users/me — some flows omit userInfo from the token
		// response; the endpoint may still carry clineUserId.
		id, err := a.fetchIdentity(ctx, tok.AccessToken)
		if err != nil {
			return IdentityResult{}, StoredCredentials{}, err
		}
		stableID, email = id.ClineUserID, id.Email
	}
	if stableID == "" {
		return IdentityResult{}, StoredCredentials{}, ErrMissingStableIdentity
	}

	stored, err := marshalClinePassToken(tok.AccessToken, tok.RefreshToken, parseClinePassExpiry(tok.ExpiresAt), tok.UserInfo)
	if err != nil {
		return IdentityResult{}, StoredCredentials{}, err
	}
	return IdentityResult{
		ExternalID: stableID,
		Email:      email,
		Plan:       "ClinePass",
		Funding:    string(FundingPaid),
		Confidence: clinePassConfidence,
		Evidence:   map[string]any{"funding_source": "clinepass_locked_paid"},
	}, stored, nil
}

// RefreshCredentials posts {refreshToken, grantType:"refresh_token"} (camelCase,
// 03 §3). Same retention rules as claude-code: keep the old refresh token when
// none is returned; keep the prior userInfo when the response carries none; a
// failed refresh returns a typed error and leaves the stored credential
// untouched.
func (a *ClinePassAdapter) RefreshCredentials(ctx context.Context, creds StoredCredentials) (StoredCredentials, error) {
	var stored clinePassStoredToken
	if err := json.Unmarshal([]byte(creds.Value), &stored); err != nil {
		return StoredCredentials{}, fmt.Errorf("providers: clinepass: refresh: parse stored credentials: %w", err)
	}
	if stored.RefreshToken == "" {
		return StoredCredentials{}, errors.New("providers: clinepass: refresh: no refresh token available")
	}
	reqBody, _ := json.Marshal(map[string]string{"refreshToken": stored.RefreshToken, "grantType": "refresh_token"})
	tok, err := a.exchange(ctx, ClinePassBaseURL+clinePassRefreshPath, reqBody)
	if err != nil {
		return StoredCredentials{}, err
	}
	newRefresh := tok.RefreshToken
	if newRefresh == "" {
		newRefresh = stored.RefreshToken
	}
	userInfo := tok.UserInfo
	if userInfo == nil {
		userInfo = stored.UserInfo
	}
	return marshalClinePassToken(tok.AccessToken, newRefresh, parseClinePassExpiry(tok.ExpiresAt), userInfo)
}

func (a *ClinePassAdapter) exchange(ctx context.Context, url string, body []byte) (clinePassTokenData, error) {
	status, respBody, err := a.postProbe(ctx, url, body)
	if err != nil {
		return clinePassTokenData{}, fmt.Errorf("providers: clinepass: token endpoint: %w", err)
	}
	if status == 401 || status == 403 {
		return clinePassTokenData{}, ErrInvalidCredential
	}
	if status < 200 || status >= 300 {
		return clinePassTokenData{}, ErrProviderUnavailable
	}
	var env clinePassEnvelope[clinePassTokenData]
	if err := json.Unmarshal(respBody, &env); err != nil {
		return clinePassTokenData{}, fmt.Errorf("providers: clinepass: parse token response: %w", err)
	}
	if !env.Success || env.Data == nil || env.Data.AccessToken == "" {
		return clinePassTokenData{}, ErrInvalidCredential
	}
	return *env.Data, nil
}

// clinePassStableIdentity resolves the stable external id from the token
// response's userInfo: clineUserId first, then subject (03 §3). Email is the
// userInfo email. Empty id = "resolve elsewhere or fail".
func clinePassStableIdentity(u *clinePassUserInfo) (stableID, email string) {
	if u == nil {
		return "", ""
	}
	if u.ClineUserID != "" {
		return u.ClineUserID, u.Email
	}
	return u.Subject, u.Email
}

// parseClinePassExpiry parses the token response's ISO-string expiresAt; a
// missing/unparseable value falls back to the legacy default (now + 1h), never
// a zero expiry.
func parseClinePassExpiry(value string) int64 {
	if value == "" {
		return time.Now().Add(clinePassDefaultExpiry * time.Second).Unix()
	}
	t, err := time.Parse(time.RFC3339, value)
	if err != nil {
		return time.Now().Add(clinePassDefaultExpiry * time.Second).Unix()
	}
	return t.Unix()
}

func marshalClinePassToken(access, refresh string, expiresAt int64, userInfo *clinePassUserInfo) (StoredCredentials, error) {
	value, err := json.Marshal(clinePassStoredToken{
		AccessToken:  access,
		RefreshToken: refresh,
		ExpiresAt:    expiresAt,
		UserInfo:     userInfo,
	})
	if err != nil {
		return StoredCredentials{}, fmt.Errorf("providers: clinepass: marshal stored credentials: %w", err)
	}
	return StoredCredentials{Value: string(value)}, nil
}

// fetchIdentity reads GET /api/v1/users/me (the credential-authentic identity
// call, also used by health). The envelope is {success, data}. clineUserId, when
// present, is the stable id; email is read when present (the primary email
// source is the token userInfo, which some flows omit).
func (a *ClinePassAdapter) fetchIdentity(ctx context.Context, accessToken string) (clinePassIdentity, error) {
	status, body, err := a.getProbe(ctx, ClinePassBaseURL+clinePassIdentityPath, accessToken)
	if err != nil {
		return clinePassIdentity{}, fmt.Errorf("providers: clinepass: fetch identity: %w", err)
	}
	if status == 401 || status == 403 {
		return clinePassIdentity{}, ErrInvalidCredential
	}
	if status < 200 || status >= 300 {
		return clinePassIdentity{}, ErrProviderUnavailable
	}
	var env clinePassEnvelope[clinePassIdentity]
	if err := json.Unmarshal(body, &env); err != nil {
		return clinePassIdentity{}, fmt.Errorf("providers: clinepass: parse identity: %w", err)
	}
	if !env.Success || env.Data == nil {
		return clinePassIdentity{}, ErrMissingStableIdentity
	}
	return *env.Data, nil
}

// FetchIdentity implements IdentityAdapter: stored userInfo first (it was
// captured at token time and carries clineUserId/subject/email), then the
// /users/me fallback. A blank stable id is a typed error, never fabricated.
func (a *ClinePassAdapter) FetchIdentity(ctx context.Context, creds StoredCredentials) (IdentityResult, error) {
	token, userInfo, err := clinePassTokenAndUserInfo(creds)
	if err != nil {
		return IdentityResult{}, err
	}
	if stableID, email := clinePassStableIdentity(userInfo); stableID != "" {
		return IdentityResult{ExternalID: stableID, Email: email, Plan: "ClinePass", Funding: string(FundingPaid), Confidence: clinePassConfidence}, nil
	}
	id, err := a.fetchIdentity(ctx, token)
	if err != nil {
		return IdentityResult{}, err
	}
	if id.ClineUserID == "" {
		return IdentityResult{}, ErrMissingStableIdentity
	}
	return IdentityResult{ExternalID: id.ClineUserID, Email: id.Email, Plan: "ClinePass", Funding: string(FundingPaid), Confidence: clinePassConfidence}, nil
}

// clinePassModelEntry is one model in the recommended-models groups.
type clinePassModelEntry struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// clinePassRecommendedModels is the REAL recommended-models shape: three
// arrays, NOT a `models` array (legacy 2026-08-03). The endpoint is PUBLIC.
type clinePassRecommendedModels struct {
	Recommended []clinePassModelEntry `json:"recommended"`
	Free        []clinePassModelEntry `json:"free"`
	ClinePass   []clinePassModelEntry `json:"clinePass"`
}

// DiscoverModels reads the PUBLIC GET /recommended-models and merges the three
// groups by id with clinePass > recommended > free priority (legacy ordering,
// 2026-08-03). Only explicit facts are reported (id + display name; chat
// capability, since the recommended list is the set of chat models clinepass
// offers). No limit fields are read, so limits stay nil.
func (a *ClinePassAdapter) DiscoverModels(ctx context.Context, creds StoredCredentials) ([]DiscoveredModel, error) {
	if _, _, err := clinePassTokenAndUserInfo(creds); err != nil {
		return nil, err
	}
	// Empty token: the recommended-models endpoint is public and must not
	// receive a workos:-prefixed Authorization header.
	status, body, err := a.getProbe(ctx, ClinePassBaseURL+clinePassModelsPath, "")
	if err != nil {
		return nil, fmt.Errorf("providers: clinepass: discover models: %w", err)
	}
	if status < 200 || status >= 300 {
		return nil, fmt.Errorf("providers: clinepass: discover models: status %d", status)
	}
	var list clinePassRecommendedModels
	if err := json.Unmarshal(body, &list); err != nil {
		return nil, fmt.Errorf("providers: clinepass: parse models: %w", err)
	}

	byID := make(map[string]DiscoveredModel)
	priority := map[string]int{"clinePass": 3, "recommended": 2, "free": 1}
	seen := make(map[string]int)
	for group, entries := range map[string][]clinePassModelEntry{
		"clinePass":   list.ClinePass,
		"recommended": list.Recommended,
		"free":        list.Free,
	} {
		for _, m := range entries {
			if m.ID == "" {
				continue
			}
			if prior, ok := seen[m.ID]; ok && prior >= priority[group] {
				continue // keep the higher-priority entry already merged
			}
			display := m.Name
			if display == "" {
				display = m.ID
			}
			seen[m.ID] = priority[group]
			byID[m.ID] = DiscoveredModel{ProviderModelID: m.ID, DisplayName: display, Capabilities: []string{"chat"}}
		}
	}
	out := make([]DiscoveredModel, 0, len(byID))
	for _, m := range byID {
		out = append(out, m)
	}
	return out, nil
}

// clinePassBalance is the data of GET /users/{id}/balance: balance is
// micro-USD (1/1,000,000 of a dollar — legacy confirmed against Cline's own
// dashboard, 2026-08-03).
type clinePassBalance struct {
	Balance *float64 `json:"balance"`
}

// clinePassUsageLimit is one entry of GET /users/me/plan/usage-limits
// (legacy ClinePassUsageLimit): five_hour / weekly / monthly rolling windows
// with percentUsed + resetsAt.
type clinePassUsageLimit struct {
	Type        string   `json:"type"`
	PercentUsed *float64 `json:"percentUsed"`
	ResetsAt    string   `json:"resetsAt"`
}

type clinePassUsageLimits struct {
	Limits []clinePassUsageLimit `json:"limits"`
}

// FetchQuota grounds a balance window on GET /users/{id}/balance (micro-USD)
// and rolling windows on GET /users/me/plan/usage-limits, exactly the paths the
// reference uses (03 §3 / legacy 2026-08-03). A missing user id or a payload
// with no grounded number yields NO windows — an empty slice is "no evidence",
// never "unlimited".
func (a *ClinePassAdapter) FetchQuota(ctx context.Context, creds StoredCredentials) (QuotaResult, error) {
	token, _, err := clinePassTokenAndUserInfo(creds)
	if err != nil {
		return QuotaResult{}, err
	}

	// 1. /users/me -> the numeric user id the balance path is keyed on.
	id, err := a.fetchUserID(ctx, token)
	if err != nil {
		return QuotaResult{}, err
	}
	if id == "" {
		return QuotaResult{}, nil // no grounded user id -> no windows
	}

	var windows []QuotaWindow

	// 2. Balance (micro-USD -> USD).
	status, body, err := a.getProbe(ctx, fmt.Sprintf(ClinePassBaseURL+clinePassBalancePath, id), token)
	if err != nil {
		return QuotaResult{}, fmt.Errorf("providers: clinepass: fetch quota: %w", err)
	}
	if status < 200 || status >= 300 {
		return QuotaResult{}, fmt.Errorf("providers: clinepass: fetch quota: status %d", status)
	}
	var balEnv clinePassEnvelope[clinePassBalance]
	if err := json.Unmarshal(body, &balEnv); err != nil {
		return QuotaResult{}, fmt.Errorf("providers: clinepass: parse balance: %w", err)
	}
	if balEnv.Success && balEnv.Data != nil && balEnv.Data.Balance != nil {
		usd := *balEnv.Data.Balance / clinePassMicroPerUSD
		windows = append(windows, QuotaWindow{
			Unit:       "credits",
			WindowType: "balance",
			Remaining:  &usd,
			Confidence: clinePassConfidence,
		})
	}

	// 3. Usage limits (five_hour / weekly / monthly percent windows).
	status, body, err = a.getProbe(ctx, ClinePassBaseURL+clinePassUsageLimitsPath, token)
	if err != nil {
		return QuotaResult{}, fmt.Errorf("providers: clinepass: fetch usage limits: %w", err)
	}
	if status >= 200 && status < 300 {
		var limitsEnv clinePassEnvelope[clinePassUsageLimits]
		if err := json.Unmarshal(body, &limitsEnv); err == nil && limitsEnv.Success && limitsEnv.Data != nil {
			for _, l := range limitsEnv.Data.Limits {
				windowType, duration, ok := clinePassUsageWindowKind(l.Type)
				if !ok {
					continue
				}
				qw := QuotaWindow{
					Unit:            "percent",
					WindowType:      windowType,
					DurationSeconds: intPtr(duration),
					Confidence:      clinePassConfidence,
				}
				if l.PercentUsed != nil {
					used := *l.PercentUsed
					qw.Used = &used
				}
				if resetAt := parseRFC3339Seconds(l.ResetsAt); resetAt != nil {
					qw.ResetAt = resetAt
				}
				windows = append(windows, qw)
			}
		}
	}

	return QuotaResult{Windows: windows}, nil
}

// fetchUserID reads GET /users/me for the numeric id the balance path needs.
// A non-2xx or an envelope without data.id returns "" (fail closed, never a
// fabricated path).
func (a *ClinePassAdapter) fetchUserID(ctx context.Context, accessToken string) (string, error) {
	status, body, err := a.getProbe(ctx, ClinePassBaseURL+clinePassIdentityPath, accessToken)
	if err != nil {
		return "", fmt.Errorf("providers: clinepass: fetch user id: %w", err)
	}
	if status == 401 || status == 403 {
		return "", ErrInvalidCredential
	}
	if status < 200 || status >= 300 {
		return "", fmt.Errorf("providers: clinepass: fetch user id: status %d", status)
	}
	var env clinePassEnvelope[struct {
		ID string `json:"id"`
	}]
	if err := json.Unmarshal(body, &env); err != nil {
		return "", fmt.Errorf("providers: clinepass: parse user: %w", err)
	}
	if !env.Success || env.Data == nil {
		return "", nil
	}
	return env.Data.ID, nil
}

// clinePassUsageWindowKind maps a usage-limit type onto a window vocabulary
// entry. if/else, not a slug switch.
func clinePassUsageWindowKind(typ string) (windowType string, duration int, ok bool) {
	if typ == "five_hour" {
		return "rolling_5h", 18000, true
	}
	if typ == "weekly" {
		return "rolling_7d", 604800, true
	}
	if typ == "monthly" {
		return "rolling_30d", 2592000, true
	}
	return "", 0, false
}

// parseRFC3339Seconds parses an RFC3339 timestamp into unix seconds, returning
// nil for absent/unparseable (never a fabricated reset).
func parseRFC3339Seconds(value string) *int64 {
	if value == "" {
		return nil
	}
	t, err := time.Parse(time.RFC3339, value)
	if err != nil {
		return nil
	}
	unix := t.Unix()
	return &unix
}

// CheckAccountHealth reuses the identity GET as the credential-authentic call.
func (a *ClinePassAdapter) CheckAccountHealth(ctx context.Context, creds StoredCredentials) (HealthObservation, error) {
	return a.checkHealth(ctx, creds, "account")
}

// CheckOfferingHealth reuses the account-level probe (no per-model endpoint).
func (a *ClinePassAdapter) CheckOfferingHealth(ctx context.Context, creds StoredCredentials, _ string) (HealthObservation, error) {
	return a.checkHealth(ctx, creds, "offering")
}

func (a *ClinePassAdapter) checkHealth(ctx context.Context, creds StoredCredentials, scope string) (HealthObservation, error) {
	token, _, err := clinePassTokenAndUserInfo(creds)
	if err != nil {
		return observationFromValidation(ValidationUnavailable, scope, time.Now().Unix()), nil
	}
	status, _, err := a.getProbe(ctx, ClinePassBaseURL+clinePassIdentityPath, token)
	if err != nil {
		return observationFromValidation(ValidationUnavailable, scope, time.Now().Unix()), nil
	}
	return observationFromValidation(classifyOAuthStatus(status), scope, time.Now().Unix()), nil
}

// clinePassTokenAndUserInfo extracts the access token (required) and the
// stored userInfo (may be nil) from the credential envelope.
func clinePassTokenAndUserInfo(creds StoredCredentials) (string, *clinePassUserInfo, error) {
	var stored clinePassStoredToken
	if err := json.Unmarshal([]byte(creds.Value), &stored); err != nil {
		return "", nil, fmt.Errorf("providers: clinepass: parse stored credentials: %w", err)
	}
	if stored.AccessToken == "" {
		return "", nil, ErrInvalidCredential
	}
	return stored.AccessToken, stored.UserInfo, nil
}

// clinePassAccessToken is retained for the seam boundary contract (health uses
// clinePassTokenAndUserInfo; some callers need just the token).
func clinePassAccessToken(creds StoredCredentials) (string, error) {
	token, _, err := clinePassTokenAndUserInfo(creds)
	return token, err
}

// RegisterClinePass registers the clinepass OAuth + Identity + Discovery +
// Quota + Health adapters into reg with the native_oauth transport and the
// openai_chat wire schema.
func RegisterClinePass(reg *Registry, postProbe ClinePassPostProbe, getProbe ClinePassGetProbe) error {
	adapter := NewClinePassAdapter(postProbe, getProbe)
	return reg.Register(Definition{
		ID:         ClinePassID,
		AuthMode:   AuthModeOAuth,
		Transport:  TransportKindNativeOAuth,
		WireSchema: WireSchemaOpenAIChat,
		OAuth:      adapter,
		Identity:   adapter,
		Discovery:  adapter,
		Quota:      adapter,
		Health:     adapter,
	})
}
