// GENERATED by validation/build-tokens.cjs from tokens/tokens.primitive.json,
// tokens/tokens.semantic.*.json and tokens/tokens.density.json — DO NOT EDIT BY HAND.
//
// The Tailwind theme extension — the third compiled token output alongside the CSS
// custom properties and the typed tokens object. Every value is a var(--…) reference
// to the generated CSS custom properties, so utilities re-resolve under data-theme /
// data-density at runtime and can never drift from the authored tokens.
// Exception: `screens` — media queries cannot read CSS custom properties, so
// breakpoints carry the literal primitive values.
// Component-layer tokens are deliberately excluded: screens compose inventory
// components and never restyle their parts.
export const venomTailwindTheme = {
  "colors": {
    "accent": {
      "active": "var(--accent-active)",
      "border": "var(--accent-border)",
      "default": "var(--accent-default)",
      "hover": "var(--accent-hover)",
      "subtle-bg": "var(--accent-subtle-bg)",
      "text": "var(--accent-text)"
    },
    "action": {
      "destructive": {
        "bg": "var(--action-destructive-bg)",
        "bg-hover": "var(--action-destructive-bg-hover)",
        "fg": "var(--action-destructive-fg)"
      },
      "disabled": {
        "bg": "var(--action-disabled-bg)",
        "fg": "var(--action-disabled-fg)"
      },
      "ghost": {
        "bg-hover": "var(--action-ghost-bg-hover)"
      },
      "primary": {
        "bg": "var(--action-primary-bg)",
        "bg-active": "var(--action-primary-bg-active)",
        "bg-hover": "var(--action-primary-bg-hover)",
        "fg": "var(--action-primary-fg)"
      },
      "secondary": {
        "bg": "var(--action-secondary-bg)",
        "bg-hover": "var(--action-secondary-bg-hover)",
        "border": "var(--action-secondary-border)",
        "fg": "var(--action-secondary-fg)"
      }
    },
    "border": {
      "default": "var(--border-default)",
      "focus": "var(--border-focus)",
      "strong": "var(--border-strong)",
      "subtle": "var(--border-subtle)"
    },
    "focus": {
      "ring": "var(--focus-ring)"
    },
    "selection": {
      "bg": "var(--selection-bg)",
      "fg": "var(--selection-fg)"
    },
    "status": {
      "critical": {
        "bg": "var(--status-critical-bg)",
        "border": "var(--status-critical-border)",
        "fg": "var(--status-critical-fg)"
      },
      "degraded": {
        "bg": "var(--status-degraded-bg)",
        "border": "var(--status-degraded-border)",
        "fg": "var(--status-degraded-fg)"
      },
      "healthy": {
        "bg": "var(--status-healthy-bg)",
        "border": "var(--status-healthy-border)",
        "fg": "var(--status-healthy-fg)"
      },
      "inactive": {
        "bg": "var(--status-inactive-bg)",
        "border": "var(--status-inactive-border)",
        "fg": "var(--status-inactive-fg)"
      },
      "info": {
        "bg": "var(--status-info-bg)",
        "border": "var(--status-info-border)",
        "fg": "var(--status-info-fg)"
      },
      "unknown": {
        "bg": "var(--status-unknown-bg)",
        "border": "var(--status-unknown-border)",
        "fg": "var(--status-unknown-fg)"
      },
      "warning": {
        "bg": "var(--status-warning-bg)",
        "border": "var(--status-warning-border)",
        "fg": "var(--status-warning-fg)"
      }
    },
    "surface": {
      "canvas": "var(--surface-canvas)",
      "inverse": "var(--surface-inverse)",
      "overlay": "var(--surface-overlay)",
      "primary": "var(--surface-primary)",
      "raised": "var(--surface-raised)",
      "scrim": "var(--surface-scrim)",
      "secondary": "var(--surface-secondary)",
      "sunken": "var(--surface-sunken)"
    },
    "text": {
      "disabled": "var(--text-disabled)",
      "inverse": "var(--text-inverse)",
      "link": "var(--text-link)",
      "link-hover": "var(--text-link-hover)",
      "muted": "var(--text-muted)",
      "on-accent": "var(--text-on-accent)",
      "primary": "var(--text-primary)",
      "secondary": "var(--text-secondary)"
    },
    "tier": {
      "lite": {
        "bg": "var(--tier-lite-bg)",
        "border": "var(--tier-lite-border)",
        "fg": "var(--tier-lite-fg)"
      },
      "max": {
        "bg": "var(--tier-max-bg)",
        "border": "var(--tier-max-border)",
        "fg": "var(--tier-max-fg)"
      },
      "pro": {
        "bg": "var(--tier-pro-bg)",
        "border": "var(--tier-pro-border)",
        "fg": "var(--tier-pro-fg)"
      }
    },
    "viz": {
      "cat": {
        "1": "var(--viz-cat-1)",
        "2": "var(--viz-cat-2)",
        "3": "var(--viz-cat-3)",
        "4": "var(--viz-cat-4)",
        "5": "var(--viz-cat-5)",
        "6": "var(--viz-cat-6)",
        "7": "var(--viz-cat-7)",
        "8": "var(--viz-cat-8)"
      },
      "seq": {
        "1": "var(--viz-seq-1)",
        "2": "var(--viz-seq-2)",
        "3": "var(--viz-seq-3)",
        "4": "var(--viz-seq-4)",
        "5": "var(--viz-seq-5)",
        "6": "var(--viz-seq-6)",
        "7": "var(--viz-seq-7)"
      }
    }
  },
  "spacing": {
    "0": "var(--space-0)",
    "1": "var(--space-1)",
    "2": "var(--space-2)",
    "3": "var(--space-3)",
    "4": "var(--space-4)",
    "5": "var(--space-5)",
    "6": "var(--space-6)",
    "8": "var(--space-8)",
    "10": "var(--space-10)",
    "12": "var(--space-12)",
    "16": "var(--space-16)",
    "20": "var(--space-20)",
    "24": "var(--space-24)",
    "32": "var(--space-32)"
  },
  "borderRadius": {
    "xs": "var(--radius-xs)",
    "sm": "var(--radius-sm)",
    "md": "var(--radius-md)",
    "lg": "var(--radius-lg)",
    "xl": "var(--radius-xl)",
    "2xl": "var(--radius-2xl)",
    "full": "var(--radius-full)"
  },
  "borderWidth": {
    "hairline": "var(--border-hairline)",
    "thick": "var(--border-thick)",
    "heavy": "var(--border-heavy)"
  },
  "fontFamily": {
    "ui": "var(--font-family-ui)",
    "mono": "var(--font-family-mono)"
  },
  "fontSize": {
    "2xs": "var(--font-size-2xs)",
    "xs": "var(--font-size-xs)",
    "sm": "var(--font-size-sm)",
    "md": "var(--font-size-md)",
    "lg": "var(--font-size-lg)",
    "xl": "var(--font-size-xl)",
    "2xl": "var(--font-size-2xl)",
    "3xl": "var(--font-size-3xl)",
    "4xl": "var(--font-size-4xl)",
    "5xl": "var(--font-size-5xl)",
    "6xl": "var(--font-size-6xl)",
    "7xl": "var(--font-size-7xl)"
  },
  "fontWeight": {
    "regular": "var(--font-weight-regular)",
    "medium": "var(--font-weight-medium)",
    "semibold": "var(--font-weight-semibold)",
    "bold": "var(--font-weight-bold)"
  },
  "lineHeight": {
    "tight": "var(--font-line-height-tight)",
    "snug": "var(--font-line-height-snug)",
    "normal": "var(--font-line-height-normal)",
    "loose": "var(--font-line-height-loose)"
  },
  "letterSpacing": {
    "normal": "var(--font-tracking-normal)",
    "wide": "var(--font-tracking-wide)",
    "wider": "var(--font-tracking-wider)"
  },
  "boxShadow": {
    "0": "var(--shadow-0)",
    "1": "var(--shadow-1)",
    "2": "var(--shadow-2)",
    "3": "var(--shadow-3)",
    "4": "var(--shadow-4)",
    "5": "var(--shadow-5)",
    "card": "var(--elevation-card)",
    "modal": "var(--elevation-modal)",
    "popover": "var(--elevation-popover)",
    "toast": "var(--elevation-toast)"
  },
  "zIndex": {
    "base": "var(--z-base)",
    "sticky": "var(--z-sticky)",
    "dropdown": "var(--z-dropdown)",
    "overlay": "var(--z-overlay)",
    "modal": "var(--z-modal)",
    "toast": "var(--z-toast)",
    "max": "var(--z-max)"
  },
  "transitionDuration": {
    "instant": "var(--duration-instant)",
    "fast": "var(--duration-fast)",
    "base": "var(--duration-base)",
    "slow": "var(--duration-slow)"
  },
  "transitionTimingFunction": {
    "standard": "var(--easing-standard)",
    "emphasized": "var(--easing-emphasized)",
    "exit": "var(--easing-exit)"
  },
  "outlineWidth": {
    "focus": "var(--focus-ring-width)"
  },
  "outlineOffset": {
    "focus": "var(--focus-ring-offset)"
  },
  "height": {
    "control-sm": "var(--density-control-height-sm)",
    "control-md": "var(--density-control-height-md)",
    "control-lg": "var(--density-control-height-lg)"
  },
  "screens": {
    "sm": "640px",
    "md": "900px",
    "lg": "1200px",
    "xl": "1440px",
    "2xl": "1760px"
  }
} as const;

/** Drop-in Tailwind preset: `presets: [venomTailwindPreset]` in tailwind.config. */
export const venomTailwindPreset = { theme: { extend: venomTailwindTheme } } as const;

export type VenomTailwindTheme = typeof venomTailwindTheme;
