/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVenomModelsRouteImport } from './routes/_authenticated/venom-models'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoutingRouteImport } from './routes/_authenticated/routing'
import { Route as AuthenticatedQuotaRouteImport } from './routes/_authenticated/quota'
import { Route as AuthenticatedProvidersRouteImport } from './routes/_authenticated/providers'
import { Route as AuthenticatedPlaygroundRouteImport } from './routes/_authenticated/playground'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated/diagnostics'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as AuthenticatedProvidersIndexRouteImport } from './routes/_authenticated/providers.index'
import { Route as AuthenticatedProvidersOauthRouteImport } from './routes/_authenticated/providers.oauth'
import { Route as AuthenticatedProvidersFreeRouteImport } from './routes/_authenticated/providers.free'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVenomModelsRoute =
  AuthenticatedVenomModelsRouteImport.update({
    id: '/venom-models',
    path: '/venom-models',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoutingRoute = AuthenticatedRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotaRoute = AuthenticatedQuotaRouteImport.update({
  id: '/quota',
  path: '/quota',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProvidersRoute = AuthenticatedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaygroundRoute = AuthenticatedPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProvidersIndexRoute =
  AuthenticatedProvidersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProvidersRoute,
  } as any)
const AuthenticatedProvidersOauthRoute =
  AuthenticatedProvidersOauthRouteImport.update({
    id: '/oauth',
    path: '/oauth',
    getParentRoute: () => AuthenticatedProvidersRoute,
  } as any)
const AuthenticatedProvidersFreeRoute =
  AuthenticatedProvidersFreeRouteImport.update({
    id: '/free',
    path: '/free',
    getParentRoute: () => AuthenticatedProvidersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/callback': typeof CallbackRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/models': typeof AuthenticatedModelsRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/playground': typeof AuthenticatedPlaygroundRoute
  '/providers': typeof AuthenticatedProvidersRouteWithChildren
  '/quota': typeof AuthenticatedQuotaRoute
  '/routing': typeof AuthenticatedRoutingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/venom-models': typeof AuthenticatedVenomModelsRoute
  '/providers/free': typeof AuthenticatedProvidersFreeRoute
  '/providers/oauth': typeof AuthenticatedProvidersOauthRoute
  '/providers/': typeof AuthenticatedProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/callback': typeof CallbackRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/models': typeof AuthenticatedModelsRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/playground': typeof AuthenticatedPlaygroundRoute
  '/quota': typeof AuthenticatedQuotaRoute
  '/routing': typeof AuthenticatedRoutingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/venom-models': typeof AuthenticatedVenomModelsRoute
  '/': typeof AuthenticatedIndexRoute
  '/providers/free': typeof AuthenticatedProvidersFreeRoute
  '/providers/oauth': typeof AuthenticatedProvidersOauthRoute
  '/providers': typeof AuthenticatedProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/callback': typeof CallbackRoute
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/models': typeof AuthenticatedModelsRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/playground': typeof AuthenticatedPlaygroundRoute
  '/_authenticated/providers': typeof AuthenticatedProvidersRouteWithChildren
  '/_authenticated/quota': typeof AuthenticatedQuotaRoute
  '/_authenticated/routing': typeof AuthenticatedRoutingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/_authenticated/venom-models': typeof AuthenticatedVenomModelsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/providers/free': typeof AuthenticatedProvidersFreeRoute
  '/_authenticated/providers/oauth': typeof AuthenticatedProvidersOauthRoute
  '/_authenticated/providers/': typeof AuthenticatedProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/callback'
    | '/api-keys'
    | '/diagnostics'
    | '/models'
    | '/overview'
    | '/playground'
    | '/providers'
    | '/quota'
    | '/routing'
    | '/settings'
    | '/usage'
    | '/venom-models'
    | '/providers/free'
    | '/providers/oauth'
    | '/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/callback'
    | '/api-keys'
    | '/diagnostics'
    | '/models'
    | '/overview'
    | '/playground'
    | '/quota'
    | '/routing'
    | '/settings'
    | '/usage'
    | '/venom-models'
    | '/'
    | '/providers/free'
    | '/providers/oauth'
    | '/providers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/callback'
    | '/_authenticated/api-keys'
    | '/_authenticated/diagnostics'
    | '/_authenticated/models'
    | '/_authenticated/overview'
    | '/_authenticated/playground'
    | '/_authenticated/providers'
    | '/_authenticated/quota'
    | '/_authenticated/routing'
    | '/_authenticated/settings'
    | '/_authenticated/usage'
    | '/_authenticated/venom-models'
    | '/_authenticated/'
    | '/_authenticated/providers/free'
    | '/_authenticated/providers/oauth'
    | '/_authenticated/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CallbackRoute: typeof CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/venom-models': {
      id: '/_authenticated/venom-models'
      path: '/venom-models'
      fullPath: '/venom-models'
      preLoaderRoute: typeof AuthenticatedVenomModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routing': {
      id: '/_authenticated/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof AuthenticatedRoutingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quota': {
      id: '/_authenticated/quota'
      path: '/quota'
      fullPath: '/quota'
      preLoaderRoute: typeof AuthenticatedQuotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/providers': {
      id: '/_authenticated/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthenticatedProvidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playground': {
      id: '/_authenticated/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AuthenticatedPlaygroundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostics': {
      id: '/_authenticated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/providers/': {
      id: '/_authenticated/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof AuthenticatedProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedProvidersRoute
    }
    '/_authenticated/providers/oauth': {
      id: '/_authenticated/providers/oauth'
      path: '/oauth'
      fullPath: '/providers/oauth'
      preLoaderRoute: typeof AuthenticatedProvidersOauthRouteImport
      parentRoute: typeof AuthenticatedProvidersRoute
    }
    '/_authenticated/providers/free': {
      id: '/_authenticated/providers/free'
      path: '/free'
      fullPath: '/providers/free'
      preLoaderRoute: typeof AuthenticatedProvidersFreeRouteImport
      parentRoute: typeof AuthenticatedProvidersRoute
    }
  }
}

interface AuthenticatedProvidersRouteChildren {
  AuthenticatedProvidersFreeRoute: typeof AuthenticatedProvidersFreeRoute
  AuthenticatedProvidersOauthRoute: typeof AuthenticatedProvidersOauthRoute
  AuthenticatedProvidersIndexRoute: typeof AuthenticatedProvidersIndexRoute
}

const AuthenticatedProvidersRouteChildren: AuthenticatedProvidersRouteChildren =
  {
    AuthenticatedProvidersFreeRoute: AuthenticatedProvidersFreeRoute,
    AuthenticatedProvidersOauthRoute: AuthenticatedProvidersOauthRoute,
    AuthenticatedProvidersIndexRoute: AuthenticatedProvidersIndexRoute,
  }

const AuthenticatedProvidersRouteWithChildren =
  AuthenticatedProvidersRoute._addFileChildren(
    AuthenticatedProvidersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedDiagnosticsRoute: typeof AuthenticatedDiagnosticsRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPlaygroundRoute: typeof AuthenticatedPlaygroundRoute
  AuthenticatedProvidersRoute: typeof AuthenticatedProvidersRouteWithChildren
  AuthenticatedQuotaRoute: typeof AuthenticatedQuotaRoute
  AuthenticatedRoutingRoute: typeof AuthenticatedRoutingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedVenomModelsRoute: typeof AuthenticatedVenomModelsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedDiagnosticsRoute: AuthenticatedDiagnosticsRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPlaygroundRoute: AuthenticatedPlaygroundRoute,
  AuthenticatedProvidersRoute: AuthenticatedProvidersRouteWithChildren,
  AuthenticatedQuotaRoute: AuthenticatedQuotaRoute,
  AuthenticatedRoutingRoute: AuthenticatedRoutingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedVenomModelsRoute: AuthenticatedVenomModelsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CallbackRoute: CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
